our %field_list = ( 'SOURCE GEOIP AS NUMBER' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.src_asnum', },
 'INVALID LENGTH FOR OPTION' =>  { '1.12.0 to 3.0.1' => 'ip.opt.len.invalid', },
 'SOURCE OR DESTINATION GEOIP AS ORGANIZATION' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.org', },
 'SOURCE GEOIP CITY' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.src_city', },
 'FRAGMENT COUNT' =>  { '1.6.0 to 3.0.1' => 'ip.fragment.count', },
 'REASSEMBLED IPV4 DATA' =>  { '1.10.0 to 3.0.1' => 'ip.reassembled.data', },
 'SOURCE OR DESTINATION ADDRESS' =>  { '1.0.0 to 3.0.1' => 'ip.addr', },
 'DEFRAGMENTATION ERROR' =>  { '1.0.0 to 3.0.1' => 'ip.fragment.error', },
 'RATE' =>  { '1.8.0 to 3.0.1' => 'ip.opt.qs_rate', },
 'DON\'T FRAGMENT' =>  { '1.0.0 to 3.0.1' => 'ip.flags.df', },
 'DESTINATION GEOIP LONGITUDE' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.dst_lon', },
 'FLAGS' =>  { '1.0.0 to 3.0.1' => 'ip.flags', },
 'TYPE OF SERVICE' =>  { '1.0.0 to 3.0.1' => 'ip.tos', },
 'DESTINATION GEOIP LATITUDE' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.dst_lat', },
 'SOURCE OR DESTINATION HOST' =>  { '1.0.0 to 3.0.1' => 'ip.host', },
 'BOGUS IP VERSION' =>  { '2.0.0 to 3.0.1' => 'ip.bogus_ip_version', },
 'DESTINATION' =>  { '1.0.0 to 3.0.1' => 'ip.dst', },
 'POINTER' =>  { '1.8.0 to 3.0.1' => 'ip.opt.ptr', },
 'TOTAL LENGTH' =>  { '1.0.0 to 3.0.1' => 'ip.len', },
 'FRAGMENT TOO LONG' =>  { '1.0.0 to 3.0.1' => 'ip.fragment.toolongfragment', },
 'ADDRESS' =>  { '2.0.0 to 3.0.1' => 'ip.opt.time_stamp_addr', },
 'DIFFERENTIATED SERVICES CODEPOINT' =>  { '1.0.0 to 3.0.1' => 'ip.dsfield.dscp', },
 'SOURCE OR DESTINATION GEOIP COUNTRY' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.country', },
 'ROUTER ALERT' =>  { '1.8.0 to 3.0.1' => 'ip.opt.ra', },
 'BAD CHECKSUM' =>  { '1.12.0 to 3.0.1' => 'ip.checksum_bad.expert', },
 'ECN-CE' =>  { '1.0.0 to 1.4.15' => 'ip.dsfield.ce', },
 'DESTINATION GEOIP AS NUMBER' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.dst_asnum', },
 'IDENTIFICATION' =>  { '1.0.0 to 3.0.1' => 'ip.id', },
 'SOURCE ROUTE HOST' =>  { '1.8.0 to 3.0.1' => 'ip.src_rt_host', },
 'EMPTY ROUTE HOST' =>  { '1.8.0 to 3.0.1' => 'ip.empty_rt_host', },
 'TIME STAMP' =>  { '2.0.0 to 3.0.1' => 'ip.opt.time_stamp', },
 'CLASS' =>  { '1.8.0 to 3.0.1' => 'ip.opt.type.class', },
 'SOURCE OR DESTINATION GEOIP AS NUMBER' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.asnum', },
 'SOURCE' =>  { '1.0.0 to 3.0.1' => 'ip.src', },
 'REASSEMBLED IPV4 IN FRAME' =>  { '1.0.0 to 3.0.1' => 'ip.reassembled_in', },
 'ORIGINATOR IP ADDRESS' =>  { '1.8.0 to 3.0.1' => 'ip.opt.originator', },
 'MULTIPLE TAIL FRAGMENTS FOUND' =>  { '1.0.0 to 3.0.1' => 'ip.fragment.multipletails', },
 'OVERFLOW' =>  { '2.0.0 to 3.0.1' => 'ip.opt.overflow', },
 'TRANSMISSION CONTROL CODE' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_rfc791_tcc', },
 'ADDITIONAL SECURITY INFO FORMAT CODE' =>  { '1.8.0 to 3.0.1' => 'ip.opt.ext_sec_add_sec_info_format_code', },
 'MALFORMED CIPSO TAG' =>  { '2.0.0 to 3.0.1' => 'ip.cipso.malformed', },
 'NOT USED' =>  { '1.8.0 to 3.0.1' => 'ip.opt.qs_unused', },
 'SOURCE GEOIP' =>  { '2.6.0 to 3.0.1' => 'ip.geoip.src_summary', },
 'SECURITY' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_rfc791_sec', },
 'TTL DIFF' =>  { '1.8.0 to 3.0.1' => 'ip.opt.qs_ttl_diff', },
 'DESTINATION GEOIP AS ORGANIZATION' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.dst_org', },
 'OUTBOUND HOP COUNT' =>  { '1.8.0 to 3.0.1' => 'ip.opt.ohc', },
 'RECORDED ROUTE' =>  { '1.8.0 to 3.0.1' => 'ip.rec_rt', },
 'SOURCE GEOIP LATITUDE' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.src_lat', },
 'COST' =>  { '1.0.0 to 3.0.1' => 'ip.tos.cost', },
 'SECURITY FLAG' =>  { '1.4.0 to 3.0.1' => 'ip.flags.sf', },
 'SOURCE GEOIP ISP' =>  { '1.2.1 to 2.4.14' => 'ip.geoip.src_isp', },
 'SOURCE OR DESTINATION GEOIP ISP' =>  { '1.2.1 to 2.4.14' => 'ip.geoip.isp', },
 'RESERVED BIT' =>  { '1.0.0 to 3.0.1' => 'ip.flags.rb', },
 'FLAG' =>  { '2.0.0 to 3.0.1' => 'ip.opt.flag', },
 'CALCULATED CHECKSUM' =>  { '1.12.0 to 3.0.1' => 'ip.checksum_calculated', },
 'COPY ON FRAGMENTATION' =>  { '1.8.0 to 3.0.1' => 'ip.opt.type.copy', },
 'HANDLING RESTRICTIONS' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_rfc791_hr', },
 'DOI' =>  { '2.0.0 to 3.0.1' => 'ip.cipso.doi', },
 'SOURCE OR DESTINATION GEOIP ISO TWO LETTER COUNTRY CODE' =>  { '2.6.0 to 3.0.1' => 'ip.geoip.country_iso', },
 'GENSER' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_genser', },
 'IPV4 FRAGMENTS' =>  { '1.0.0 to 3.0.1' => 'ip.fragments', },
 'CLASSIFICATION LEVEL' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_cl', },
 'SOURCE OR DESTINATION GEOIP CITY' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.city', },
 'SOURCE GEOIP COUNTRY' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.src_country', },
 'DESTINATION GEOIP ISO TWO LETTER COUNTRY CODE' =>  { '2.6.0 to 3.0.1' => 'ip.geoip.dst_country_iso', },
 'SIOP-ESI' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_siop_esi', },
 'SUBOPTION WOULD GO PAST END OF OPTION' =>  { '1.12.0 to 3.0.1' => 'ip.subopt_too_long', },
 'RESERVED' =>  { '1.8.0 to 3.0.1' => 'ip.opt.qs_reserved', },
 'BOGUS IP LENGTH' =>  { '1.12.0 to 3.0.1' => 'ip.bogus_ip_length', },
 'PROTOCOL' =>  { '1.0.0 to 3.0.1' => 'ip.proto', },
 'TIME TO LIVE' =>  { '1.0.0 to 3.0.1' => 'ip.ttl', '1.12.0 to 3.0.1' => 'ip.ttl.lncb', },
 'CATEGORIES' =>  { '2.0.0 to 3.0.1' => 'ip.cipso.categories', },
 'SOURCE GEOIP AS ORGANIZATION' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.src_org', },
 'BAD' =>  { '1.0.0 to 2.0.16' => 'ip.checksum_bad', },
 'SOURCE HOST' =>  { '1.0.0 to 3.0.1' => 'ip.src_host', },
 'DELAY' =>  { '1.0.0 to 3.0.1' => 'ip.tos.delay', },
 'PACKET HAS EVIL INTENT' =>  { '1.12.0 to 3.0.1' => 'ip.evil_packet', },
 'SOURCE OR DESTINATION GEOIP LATITUDE' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.lat', },
 'SCI' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_sci', },
 'RELIABILITY' =>  { '1.0.0 to 3.0.1' => 'ip.tos.reliability', },
 'SOURCE GEOIP ISO TWO LETTER COUNTRY CODE' =>  { '2.6.0 to 3.0.1' => 'ip.geoip.src_country_iso', },
 'ECN-CAPABLE TRANSPORT (ECT)' =>  { '1.0.0 to 1.4.15' => 'ip.dsfield.ect', },
 'SOURCE ROUTE' =>  { '1.8.0 to 3.0.1' => 'ip.src_rt', },
 'ID NUMBER' =>  { '1.8.0 to 3.0.1' => 'ip.opt.id_number', },
 'RETURN HOP COUNT' =>  { '1.8.0 to 3.0.1' => 'ip.opt.rhc', },
 'DESTINATION HOST' =>  { '1.0.0 to 3.0.1' => 'ip.dst_host', },
 'TAG DATA' =>  { '2.0.0 to 3.0.1' => 'ip.cipso.tag_data', },
 'NSA' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_nsa', },
 'RECORDED ROUTE HOST' =>  { '1.8.0 to 3.0.1' => 'ip.rec_rt_host', },
 'FIELD TERMINATION INDICATOR' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_fti', },
 'VERSION' =>  { '1.0.0 to 3.0.1' => 'ip.version', },
 'BOGUS IP HEADER LENGTH' =>  { '3.0.0 to 3.0.1' => 'ip.bogus_header_length', },
 'CONFLICTING DATA IN FRAGMENT OVERLAP' =>  { '1.0.0 to 3.0.1' => 'ip.fragment.overlap.conflict', },
 'DESTINATION GEOIP COUNTRY' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.dst_country', },
 'DESTINATION GEOIP ISP' =>  { '1.2.1 to 2.4.14' => 'ip.geoip.dst_isp', },
 'EXPLICIT CONGESTION NOTIFICATION' =>  { '1.6.0 to 3.0.1' => 'ip.dsfield.ecn', },
 'POINTER POINTS BEFORE FIRST ADDRESS' =>  { '1.12.0 to 3.0.1' => 'ip.opt.ptr.before_address', },
 'FUNCTION' =>  { '1.8.0 to 3.0.1' => 'ip.opt.qs_func', },
 'COMPARTMENTS' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_rfc791_comp', },
 'PRECEDENCE' =>  { '1.0.0 to 3.0.1' => 'ip.tos.precedence', },
 'LENGTH' =>  { '1.8.0 to 3.0.1' => 'ip.opt.len', },
 'ADDITIONAL SECURITY INFO' =>  { '1.8.0 to 3.0.1' => 'ip.opt.ext_sec_add_sec_info', },
 'TAG TYPE' =>  { '2.0.0 to 3.0.1' => 'ip.cipso.tag_type', },
 'DESTINATION GEOIP CITY' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.dst_city', },
 'QS NONCE' =>  { '1.8.0 to 3.0.1' => 'ip.opt.qs_nonce', },
 'SENSITIVITY LEVEL' =>  { '2.0.0 to 3.0.1' => 'ip.cipso.sensitivity_level', },
 'STREAM IDENTIFIER' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sid', },
 'DESTINATION GEOIP' =>  { '2.6.0 to 3.0.1' => 'ip.geoip.dst_summary', },
 'GOOD' =>  { '1.0.0 to 2.0.16' => 'ip.checksum_good', },
 'SOURCE OR DESTINATION GEOIP LONGITUDE' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.lon', },
 'NUMBER' =>  { '1.8.0 to 3.0.1' => 'ip.opt.type.number', },
 'HEADER CHECKSUM' =>  { '1.0.0 to 3.0.1' => 'ip.checksum', },
 'EMPTY ROUTE' =>  { '1.8.0 to 3.0.1' => 'ip.empty_rt', },
 'HEADER CHECKSUM STATUS' =>  { '2.2.0 to 3.0.1' => 'ip.checksum.status', },
 'DOE' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_doe', },
 'MTU' =>  { '1.8.0 to 3.0.1' => 'ip.opt.mtu', },
 'THROUGHPUT' =>  { '1.0.0 to 3.0.1' => 'ip.tos.throughput', },
 'SOURCE GEOIP LONGITUDE' =>  { '1.2.1 to 3.0.1' => 'ip.geoip.src_lon', },
 'CURRENT ROUTE HOST' =>  { '1.8.0 to 3.0.1' => 'ip.cur_rt_host', },
 'PROTECTION AUTHORITY FLAGS' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_flags', },
 'MORE FRAGMENTS' =>  { '1.0.0 to 3.0.1' => 'ip.flags.mf', },
 'TYPE' =>  { '1.8.0 to 3.0.1' => 'ip.opt.type', },
 'IPV4 FRAGMENT' =>  { '1.0.0 to 3.0.1' => 'ip.fragment', },
 'FRAGMENT OVERLAP' =>  { '1.0.0 to 3.0.1' => 'ip.fragment.overlap', },
 'CURRENT ROUTE' =>  { '1.8.0 to 3.0.1' => 'ip.cur_rt', },
 'POINTER POINTS TO MIDDLE OF ADDRESS' =>  { '1.12.0 to 3.0.1' => 'ip.opt.ptr.middle_address', },
 'QS TTL' =>  { '1.8.0 to 3.0.1' => 'ip.opt.qs_ttl', },
 'HEADER LENGTH' =>  { '1.0.0 to 3.0.1' => 'ip.hdr_len', },
 'PADDING' =>  { '1.8.0 to 3.0.1' => 'ip.opt.padding', },
 'REASSEMBLED IPV4 LENGTH' =>  { '1.4.0 to 3.0.1' => 'ip.reassembled.length', },
 'DIFFERENTIATED SERVICES FIELD' =>  { '1.0.0 to 3.0.1' => 'ip.dsfield', },
 'UNASSIGNED' =>  { '1.8.0 to 3.0.1' => 'ip.opt.sec_prot_auth_unassigned', },
 'FRAGMENT OFFSET' =>  { '1.0.0 to 3.0.1' => 'ip.frag_offset', },
 '4 NOP IN A ROW - A ROUTER MAY HAVE REMOVED SOME OPTIONS' =>  { '1.12.0 to 3.0.1' => 'ip.nop', },
 'IP ADDRESS' =>  { '1.8.0 to 3.0.1' => 'ip.opt.addr', },
); 
1;