our %field_list = ( 'VIA' =>  { '1.0.0 to 3.0.1' => 'sip.Via', },
 'USER-TO-USER' =>  { '1.8.0 to 3.0.1' => 'sip.uui', },
 'MESSAGE HEADER' =>  { '1.0.0 to 3.0.1' => 'sip.msg_hdr', },
 'SUBSCRIPTION-STATE' =>  { '1.0.0 to 3.0.1' => 'sip.Subscription-State', },
 'P-VISITED-NETWORK-ID' =>  { '1.0.0 to 3.0.1' => 'sip.P-Visited-Network-ID', },
 'SECURITY-VERIFY' =>  { '1.0.0 to 3.0.1' => 'sip.Security-Verify', },
 'PORT2' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.port2', },
 'INTEGRITY KEY' =>  { '1.0.0 to 3.0.1' => 'sip.auth.ik', },
 'PROXY-REQUIRE' =>  { '1.0.0 to 3.0.1' => 'sip.Proxy-Require', },
 'SEQUENCE NUMBER' =>  { '1.0.0 to 3.0.1' => 'sip.CSeq.seq', },
 'ROUTE URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.Route.param', },
 'TARGET-DIALOG' =>  { '1.0.0 to 3.0.1' => 'sip.Target-Dialog', },
 'TEXT' =>  { '2.4.0 to 3.0.1' => 'sip.reason_text', },
 'NEXT NONCE' =>  { '1.0.0 to 3.0.1' => 'sip.auth.nextnonce', },
 'DIVERSION' =>  { '1.6.0 to 3.0.1' => 'sip.Diversion', },
 'MIN-EXPIRES' =>  { '1.0.0 to 3.0.1' => 'sip.Min-Expires', },
 'SESSION-ID' =>  { '2.0.0 to 3.0.1' => 'sip.Session-ID', },
 'DATE' =>  { '1.0.0 to 3.0.1' => 'sip.Date', },
 'SERVICE PRIORITY' =>  { '2.4.0 to 3.0.1' => 'sip.service_priority', },
 'RECV-INFO' =>  { '1.6.0 to 3.0.1' => 'sip.Recv-Info', },
 'PORT-C' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.port_c', },
 'ALERT-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.Alert-Info', },
 'REQUEST-URI HOST PORT' =>  { '1.2.0 to 3.0.1' => 'sip.r-uri.port', },
 '[SECURITY-MECHANISM]' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism', },
 'SECURITY-SERVER' =>  { '1.0.0 to 3.0.1' => 'sip.Security-Server', },
 'RPORT' =>  { '1.0.0 to 3.0.1' => 'sip.Via.rport', },
 'REFER-SUB' =>  { '1.0.0 to 3.0.1' => 'sip.Refer-Sub', },
 'RECEIVED' =>  { '1.0.0 to 3.0.1' => 'sip.Via.received', },
 'SENT-BY PORT' =>  { '1.0.0 to 3.0.1' => 'sip.Via.sent-by.port', },
 'P-DCS-LAES' =>  { '1.0.0 to 3.0.1' => 'sip.P-DCS-LAES', },
 'UTRAN-CELL-ID-3GPP' =>  { '2.2.0 to 3.0.1' => 'sip.P-Access-Network-Info.utran-cell-id-3gpp', },
 'SIP SECURITY-MECHANISM HEADER MALFORMED' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.malformed', },
 'MAX-BREADTH' =>  { '1.2.0 to 3.0.1' => 'sip.Max-Breadth', },
 'SIP PPI USER PART' =>  { '1.2.0 to 3.0.1' => 'sip.ppi.user', },
 'PRIORITY' =>  { '1.0.0 to 3.0.1' => 'sip.Priority', },
 'SIP TC ADDRESS' =>  { '1.2.0 to 3.0.1' => 'sip.tc.addr', },
 'ROUTE URI' =>  { '1.8.0 to 3.0.1' => 'sip.Route.uri', },
 'P-ASSERTED-IDENTITY' =>  { '1.0.0 to 3.0.1' => 'sip.P-Asserted-Identity', },
 'REASON-PHRASE' =>  { '1.10.0 to 3.0.1' => 'sip.Reason-Phrase', },
 'PATH URI' =>  { '2.0.0 to 3.0.1' => 'sip.Path.uri', },
 'REALM' =>  { '1.0.0 to 3.0.1' => 'sip.auth.realm', },
 'REQUEST-DISPOSITION' =>  { '1.0.0 to 3.0.1' => 'sip.Request-Disposition', },
 'REJECT-CONTACT' =>  { '1.0.0 to 3.0.1' => 'sip.Reject-Contact', },
 'ALLOW' =>  { '1.0.0 to 3.0.1' => 'sip.Allow', },
 'RSEQ SEQUENCE NUMBER' =>  { '1.0.0 to 3.0.1' => 'sip.RAck.RSeq.seq', },
 'SIP TO URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.to.param', },
 'REPLY-TO' =>  { '1.0.0 to 3.0.1' => 'sip.Reply-To', },
 'CALL-ID' =>  { '1.0.0 to 3.0.1' => 'sip.Call-ID', },
 'CONTACT URI USER PART' =>  { '1.4.0 to 3.0.1' => 'sip.contact.user', },
 'P-USER-DATABASE' =>  { '1.0.0 to 3.0.1' => 'sip.P-User-Database', },
 'ALG' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.alg', },
 'SESSION-EXPIRES' =>  { '1.0.0 to 3.0.1' => 'sip.Session-Expires', },
 'SIP PMISS HOST PORT' =>  { '1.2.0 to 3.0.1' => 'sip.pmiss.port', },
 'REQUEST-URI HOST PART' =>  { '1.2.0 to 3.0.1' => 'sip.r-uri.host', },
 'CONTENT-ENCODING' =>  { '1.0.0 to 3.0.1' => 'sip.Content-Encoding', },
 'MESSAGE BODY' =>  { '1.0.0 to 3.0.1' => 'sip.msg_body', },
 'SIP TC USER PART' =>  { '1.2.0 to 3.0.1' => 'sip.tc.user', },
 'ACCEPT-RESOURCE-PRIORITY' =>  { '1.0.0 to 3.0.1' => 'sip.Accept-Resource-Priority', },
 'RACK' =>  { '1.0.0 to 3.0.1' => 'sip.RAck', },
 'RECORD-ROUTE URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.Record-Route.param', },
 'PROT' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.prot', },
 'RECORD-ROUTE HOST PART' =>  { '1.8.0 to 3.0.1' => 'sip.Record-Route.host', },
 'P-DCS-BILLING-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.P-DCS-Billing-Info', },
 'ROUTE USERINFO' =>  { '1.8.0 to 3.0.1' => 'sip.Route.user', },
 'PORT-S' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.port_s', },
 'SIP TC HOST PORT' =>  { '1.2.0 to 3.0.1' => 'sip.tc.port', },
 'REQUEST-LINE' =>  { '1.0.0 to 3.0.1' => 'sip.Request-Line', },
 'P-PREFERRED-IDENTITY' =>  { '1.0.0 to 3.0.1' => 'sip.P-Preferred-Identity', },
 'ROUTE HOST PART' =>  { '1.8.0 to 3.0.1' => 'sip.Route.host', },
 'P-SERVED-USER' =>  { '1.4.0 to 3.0.1' => 'sip.P-Served-User', },
 'RESOURCE-PRIORITY' =>  { '1.0.0 to 3.0.1' => 'sip.Resource-Priority', },
 'CONTACT' =>  { '1.0.0 to 3.0.1' => 'sip.Contact', },
 'SIP PAI HOST PORT' =>  { '1.2.0 to 3.0.1' => 'sip.pai.port', },
 'REMOTE-UUID' =>  { '2.0.0 to 3.0.1' => 'sip.Session-ID.remote_uuid', },
 'SERVICE-ROUTE HOST PORT' =>  { '2.0.0 to 3.0.1' => 'sip.Service-Route.port', },
 'IF_MATCH' =>  { '1.0.0 to 3.0.1' => 'sip.If_Match', },
 'CONTENT-DISPOSITION' =>  { '1.0.0 to 3.0.1' => 'sip.Content-Disposition', },
 'SIP PMISS HOST PART' =>  { '1.2.0 to 3.0.1' => 'sip.pmiss.host', },
 'OVERLOAD CONTROL VALIDITY' =>  { '2.4.0 to 3.0.1' => 'sip.Via.oc_validity', },
 'PATH URI PARAMETER' =>  { '2.0.0 to 3.0.1' => 'sip.Path.param', },
 'ROUTE HOST PORT' =>  { '1.8.0 to 3.0.1' => 'sip.Route.port', },
 'PATH HOST PORT' =>  { '2.0.0 to 3.0.1' => 'sip.Path.port', },
 'SIGCOMP IDENTIFIER' =>  { '1.0.0 to 3.0.1' => 'sip.Via.sigcomp-id', },
 'SIP TO ADDRESS' =>  { '1.0.0 to 3.0.1' => 'sip.to.addr', },
 'ACCEPT' =>  { '1.0.0 to 3.0.1' => 'sip.Accept', },
 'NONCE VALUE' =>  { '1.0.0 to 3.0.1' => 'sip.auth.nonce', },
 'OVERLOAD CONTROL SEQUENCE TIME STAMP' =>  { '2.6.0 to 3.0.1' => 'sip.Via.oc_seq.ts', },
 'STALE FLAG' =>  { '1.0.0 to 3.0.1' => 'sip.auth.stale', },
 'OPAQUE VALUE' =>  { '1.0.0 to 3.0.1' => 'sip.auth.opaque', },
 'INVALID RETRY_AFTER VALUE' =>  { '3.0.0 to 3.0.1' => 'sip.retry_after.invalid', },
 'RETRY-AFTER' =>  { '1.0.0 to 3.0.1' => 'sip.Retry-After', },
 'URI' =>  { '1.0.0 to 1.2.18' => 'sip.uri', },
 'IDENTITY-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.Identity-info', },
 'ACCESS-TYPE' =>  { '2.2.0 to 3.0.1' => 'sip.P-Access-Network-Info.access-type', },
 'P-CALLED-PARTY-ID' =>  { '1.0.0 to 3.0.1' => 'sip.P-Called-Party-ID', },
 'RSEQ' =>  { '1.0.0 to 3.0.1' => 'sip.RSeq', },
 'OVERLOAD CONTROL ALGORITHM' =>  { '2.4.0 to 3.0.1' => 'sip.Via.oc_algo', },
 'SERVICE-ROUTE' =>  { '1.0.0 to 3.0.1' => 'sip.Service-Route', },
 'CYPHERING KEY' =>  { '1.0.0 to 3.0.1' => 'sip.auth.ck', },
 'INVALID STATUS-CODE' =>  { '2.4.0 to 3.0.1' => 'sip.Status-Code.invalid', },
 'SIP PAI HOST PART' =>  { '1.2.0 to 3.0.1' => 'sip.pai.host', },
 'CSEQ' =>  { '1.0.0 to 3.0.1' => 'sip.CSeq', },
 'REFER-TO' =>  { '1.0.0 to 3.0.1' => 'sip.Refer-To', },
 'PROXY-AUTHENTICATE' =>  { '1.0.0 to 3.0.1' => 'sip.Proxy-Authenticate', },
 'IDENTITY' =>  { '1.0.0 to 3.0.1' => 'sip.Identity', },
 'P-MEDIA-AUTHORIZATION' =>  { '1.0.0 to 3.0.1' => 'sip.P-Media-Authorization', },
 'SPI-C' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.spi_c', },
 'COMP' =>  { '1.0.0 to 3.0.1' => 'sip.Via.comp', },
 'SIP TO ADDRESS HOST PART' =>  { '1.2.0 to 3.0.1' => 'sip.to.host', },
 'ALLOW-EVENTS' =>  { '1.0.0 to 3.0.1' => 'sip.Allow-Events', },
 'HEADER HAS NO COLON AFTER THE NAME' =>  { '2.0.0 to 3.0.1' => 'sip.header_no_colon', },
 'PATH HOST PART' =>  { '2.0.0 to 3.0.1' => 'sip.Path.host', },
 'SIP PPI HOST PORT' =>  { '1.2.0 to 3.0.1' => 'sip.ppi.port', },
 'CSEQ SEQUENCE NUMBER' =>  { '1.0.0 to 3.0.1' => 'sip.RAck.CSeq.seq', },
 'INFO-PACKAGE' =>  { '1.6.0 to 3.0.1' => 'sip.Info-Package', },
 'INVALID AUTHORIZATION RESPONSE FOR KNOWN CREDENTIALS' =>  { '2.4.0 to 3.0.1' => 'sip.authorization.invalid', },
 'REQUEST-URI USER PART' =>  { '1.2.0 to 3.0.1' => 'sip.r-uri.user', },
 'CONTACT PARAMETER' =>  { '1.4.0 to 3.0.1' => 'sip.contact.parameter', },
 'EVENT' =>  { '1.0.0 to 3.0.1' => 'sip.Event', },
 'SIP TO ADDRESS HOST PORT' =>  { '1.2.0 to 3.0.1' => 'sip.to.port', },
 'AUTHENTICATION' =>  { '1.0.0 to 3.0.1' => 'sip.auth', },
 'SIP TC URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.tc.param', },
 'SIP FROM ADDRESS' =>  { '1.0.0 to 3.0.1' => 'sip.from.addr', },
 'AUTHORIZATION' =>  { '1.0.0 to 3.0.1' => 'sip.Authorization', },
 'SIP PAI USER PART' =>  { '1.2.0 to 3.0.1' => 'sip.pai.user', },
 'AUTHENTICATION TOKEN' =>  { '1.0.0 to 3.0.1' => 'sip.auth.auts', },
 'SIP PPI URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.ppi.param', },
 'USERNAME' =>  { '1.0.0 to 3.0.1' => 'sip.auth.username', },
 'SIP TC HOST PART' =>  { '1.2.0 to 3.0.1' => 'sip.tc.host', },
 'CONTINUATION DATA' =>  { '2.0.0 to 3.0.1' => 'sip.continuation', },
 'P-CHARGING-VECTOR' =>  { '1.0.0 to 3.0.1' => 'sip.P-Charging-Vector', },
 'SIP FROM TAG' =>  { '1.8.0 to 3.0.1' => 'sip.from.tag', },
 'POLICY-CONTACT' =>  { '1.10.0 to 3.0.1' => 'sip.Policy_Contact', },
 'CONTACT URI HOST PART' =>  { '1.4.0 to 3.0.1' => 'sip.contact.host', },
 'ORGANIZATION' =>  { '1.0.0 to 3.0.1' => 'sip.Organization', },
 'SUPPORTED' =>  { '1.0.0 to 3.0.1' => 'sip.Supported', },
 'IN-REPLY-TO' =>  { '1.0.0 to 3.0.1' => 'sip.In-Reply-To', },
 'NONCE COUNT' =>  { '1.0.0 to 3.0.1' => 'sip.auth.nc', },
 'SIP TC TARGET URI' =>  { '1.2.0 to 3.0.1' => 'sip.tc.target-uri', },
 'SIP TO TAG' =>  { '1.8.0 to 3.0.1' => 'sip.to.tag', },
 'SIP PAI ADDRESS' =>  { '1.2.0 to 3.0.1' => 'sip.pai.addr', },
 'SIP TAG' =>  { '1.0.0 to 3.0.1' => 'sip.tag', },
 'ERROR-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.Error-Info', },
 'STATUS-CODE' =>  { '1.0.0 to 3.0.1' => 'sip.Status-Code', },
 'REQUEST URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.r-uri.param', },
 'CONTACT URI' =>  { '1.4.0 to 3.0.1' => 'sip.contact.uri', },
 'SUBJECT' =>  { '1.0.0 to 3.0.1' => 'sip.Subject', },
 'SESS-ID' =>  { '2.0.0 to 3.0.1' => 'sip.Session-ID.sess_id', },
 'RECORD-ROUTE USERINFO' =>  { '1.8.0 to 3.0.1' => 'sip.Record-Route.user', },
 'SECURITY-CLIENT' =>  { '1.0.0 to 3.0.1' => 'sip.Security-Client', },
 'DIGEST AUTHENTICATION RESPONSE' =>  { '1.0.0 to 3.0.1' => 'sip.auth.digest.response', },
 'SUPPRESS-IF-MATCH' =>  { '1.10.0 to 3.0.1' => 'sip.Suppress_If_Match', },
 'CONTENT-TYPE' =>  { '1.0.0 to 3.0.1' => 'sip.Content-Type', },
 'EALG' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.ealg', },
 'PERMISSION-MISSING' =>  { '1.2.0 to 3.0.1' => 'sip.Permission-Missing', },
 'SIP FROM ADDRESS HOST PORT' =>  { '1.2.0 to 3.0.1' => 'sip.from.port', },
 'AUTHENTICATION SCHEME' =>  { '1.0.0 to 3.0.1' => 'sip.auth.scheme', },
 'OVERLOAD CONTROL SEQUENCE' =>  { '2.4.0 to 3.0.1' => 'sip.Via.oc_seq', },
 'PRIVACY' =>  { '1.0.0 to 3.0.1' => 'sip.Privacy', },
 'SIP PMISS URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.pmiss.param', },
 'FROM' =>  { '1.0.0 to 3.0.1' => 'sip.From', },
 'RESENT PACKET' =>  { '1.0.0 to 3.0.1' => 'sip.resend', },
 'SIP DISPLAY INFO' =>  { '1.0.0 to 3.0.1' => 'sip.display.info', },
 'CONTENT-LANGUAGE' =>  { '1.0.0 to 3.0.1' => 'sip.Content-Language', },
 'SPI-S' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.spi_s', },
 'HISTORY-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.History-Info', },
 'GEOLOCATION-ROUTING' =>  { '1.10.0 to 3.0.1' => 'sip.Geolocation_Routing', },
 'POLICY-ID' =>  { '1.10.0 to 3.0.1' => 'sip.Policy_ID', },
 'SIP PMISS ADDRESS' =>  { '1.2.0 to 3.0.1' => 'sip.pmiss.addr', },
 'AUTHENTICATION DOMAIN' =>  { '1.0.0 to 3.0.1' => 'sip.auth.domain', },
 'SIP PPI ADDRESS' =>  { '1.2.0 to 3.0.1' => 'sip.ppi.addr', },
 'SUSPECTED RESEND OF FRAME' =>  { '1.0.0 to 3.0.1' => 'sip.resend-original', },
 'JOIN' =>  { '1.0.0 to 3.0.1' => 'sip.Join', },
 'UNRECOGNISED SIP HEADER' =>  { '1.12.0 to 3.0.1' => 'sip.unrecognized_header', },
 'PATH USERINFO' =>  { '2.0.0 to 3.0.1' => 'sip.Path.user', },
 'P-PREFERRED-SERVICE' =>  { '1.6.0 to 3.0.1' => 'sip.P-Preferred-Service', },
 'QOP' =>  { '1.0.0 to 3.0.1' => 'sip.auth.qop', },
 'RAW SIP LINE' =>  { '1.0.0 to 1.0.16' => 'raw_sip.line', },
 'RESPONSE AUTH' =>  { '1.0.0 to 3.0.1' => 'sip.auth.rspauth', },
 'RECORD-ROUTE HOST PORT' =>  { '1.8.0 to 3.0.1' => 'sip.Record-Route.port', },
 'REASON PROTOCOLS' =>  { '2.0.0 to 3.0.1' => 'sip.reason_protocols', },
 'BRANCH' =>  { '1.0.0 to 3.0.1' => 'sip.Via.branch', },
 'CSEQ METHOD' =>  { '1.0.0 to 3.0.1' => 'sip.RAck.CSeq.method', },
 'TTL' =>  { '1.0.0 to 3.0.1' => 'sip.Via.ttl', },
 'AUTHENTICATION URI' =>  { '1.0.0 to 3.0.1' => 'sip.auth.uri', },
 'FLOW-TIMER' =>  { '1.6.0 to 3.0.1' => 'sip.Flow-Timer', },
 'CONTENT-LENGTH' =>  { '1.0.0 to 3.0.1' => 'sip.Content-Length', },
 'PORT1' =>  { '1.12.0 to 3.0.1' => 'sip.sec_mechanism.port1', },
 'SENT-BY ADDRESS' =>  { '1.0.0 to 3.0.1' => 'sip.Via.sent-by.address', },
 'P-ASSOCIATED-URI' =>  { '1.0.0 to 3.0.1' => 'sip.P-Associated-URI', },
 'RESPONSE TIME (MS)' =>  { '1.2.0 to 3.0.1' => 'sip.response-time', },
 'SIP FROM URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.from.param', },
 'SIP PPI HOST PART' =>  { '1.2.0 to 3.0.1' => 'sip.ppi.host', },
 'HEADER NOT TERMINATED BY EMPTY LINE (CRLF)' =>  { '1.12.0 to 3.0.1' => 'sip.header_not_terminated', },
 'GENERATED CALL-ID' =>  { '3.0.0 to 3.0.1' => 'sip.call_id_generated', },
 'REPLACES' =>  { '1.0.0 to 3.0.1' => 'sip.Replaces', },
 'SERVICE-ROUTE URI' =>  { '2.0.0 to 3.0.1' => 'sip.Service-Route.uri', },
 'WWW-AUTHENTICATE' =>  { '1.0.0 to 3.0.1' => 'sip.WWW-Authenticate', },
 'CONTACT BINDING' =>  { '1.0.0 to 1.2.18' => 'sip.contact.binding', },
 'P-ANSWER-STATE' =>  { '1.0.0 to 3.0.1' => 'sip.P-Answer-State', },
 'P-DCS-TRACE-PARTY-ID' =>  { '1.0.0 to 3.0.1' => 'sip.P-DCS-Trace-Party-ID', },
 'CONTACT URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.contact.param', },
 'TRANSPORT' =>  { '1.0.0 to 3.0.1' => 'sip.Via.transport', },
 'EXPIRES' =>  { '1.0.0 to 3.0.1' => 'sip.Expires', },
 'WARNING' =>  { '1.0.0 to 3.0.1' => 'sip.Warning', },
 'OVERLOAD CONTROL' =>  { '2.4.0 to 3.0.1' => 'sip.Via.oc', },
 'P-ASSERTED-SERVICE' =>  { '1.6.0 to 3.0.1' => 'sip.P-Asserted-Service', },
 'USER-AGENT' =>  { '1.0.0 to 3.0.1' => 'sip.User-Agent', },
 'REQUEST-URI' =>  { '1.2.0 to 3.0.1' => 'sip.r-uri', },
 'ACCEPT-CONTACT' =>  { '1.0.0 to 3.0.1' => 'sip.Accept-Contact', },
 'MIME-VERSION' =>  { '1.0.0 to 3.0.1' => 'sip.MIME-Version', },
 'SIP PAI URI PARAMETER' =>  { '1.8.0 to 3.0.1' => 'sip.pai.param', },
 'UNSUPPORTED' =>  { '1.0.0 to 3.0.1' => 'sip.Unsupported', },
 'ICID-VALUE' =>  { '2.6.0 to 3.0.1' => 'sip.icid_value', },
 'REQUIRE' =>  { '1.0.0 to 3.0.1' => 'sip.Require', },
 'SIP FROM ADDRESS HOST PART' =>  { '1.2.0 to 3.0.1' => 'sip.from.host', },
 'GEOLOCATION' =>  { '1.10.0 to 3.0.1' => 'sip.Geolocation', },
 'OVERLOAD CONTROL VALUE' =>  { '2.6.0 to 3.0.1' => 'sip.Via.oc_val', },
 'PARAM' =>  { '2.0.0 to 3.0.1' => 'sip.Session-ID.param', },
 'ALGORITHM' =>  { '1.0.0 to 3.0.1' => 'sip.auth.algorithm', },
 'ACCEPT-ENCODING' =>  { '1.0.0 to 3.0.1' => 'sip.Accept-Encoding', },
 'MADDR' =>  { '1.0.0 to 3.0.1' => 'sip.Via.maddr', },
 'ICID-GEN-ADDR' =>  { '2.6.0 to 3.0.1' => 'sip.icid_gen_addr', },
 'ACCEPT-LANGUAGE' =>  { '1.0.0 to 3.0.1' => 'sip.Accept-Language', },
 'TO' =>  { '1.0.0 to 3.0.1' => 'sip.To', },
 'STATUS-LINE' =>  { '1.0.0 to 3.0.1' => 'sip.Status-Line', },
 'RELEASE TIME (MS)' =>  { '1.2.0 to 3.0.1' => 'sip.release-time', },
 'CALL-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.Call-Info', },
 'RECORD-ROUTE URI' =>  { '1.8.0 to 3.0.1' => 'sip.Record-Route.uri', },
 'METHOD' =>  { '1.0.0 to 3.0.1' => 'sip.CSeq.method', },
 'SIP PMISS USER PART' =>  { '1.2.0 to 3.0.1' => 'sip.pmiss.user', },
 'ANSWER-MODE' =>  { '1.2.0 to 3.0.1' => 'sip.Answer-Mode', },
 'CNONCE VALUE' =>  { '1.0.0 to 3.0.1' => 'sip.auth.cnonce', },
 'TIMESTAMP' =>  { '1.0.0 to 3.0.1' => 'sip.Timestamp', },
 'INVALID CONTENT_LENGTH' =>  { '2.4.0 to 3.0.1' => 'sip.content_length.invalid', },
 'RECORD-ROUTE' =>  { '1.0.0 to 3.0.1' => 'sip.Record-Route', },
 'P-EARLY-MEDIA' =>  { '1.0.0 to 3.0.1' => 'sip.P-Early-Media', },
 'LOCAL-UUID' =>  { '2.0.0 to 3.0.1' => 'sip.Session-ID.local_uuid', },
 'REFERED BY' =>  { '1.0.0 to 3.0.1' => 'sip.Refered-by', },
 'ETAG' =>  { '1.0.0 to 3.0.1' => 'sip.ETag', },
 'MIN-SE' =>  { '1.0.0 to 3.0.1' => 'sip.Min-SE', },
 'P-REFUSED-URI-LIST' =>  { '1.4.0 to 3.0.1' => 'sip.P-Refused-URI-List', },
 'P-ACCESS-NETWORK-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.P-Access-Network-Info', },
 'PRIV-ANSWER-MODE' =>  { '1.2.0 to 3.0.1' => 'sip.Priv-Answer-mode', },
 'FEATURE CAP' =>  { '2.4.0 to 3.0.1' => 'sip.feature_cap', },
 'MAX-FORWARDS' =>  { '1.0.0 to 3.0.1' => 'sip.Max-Forwards', },
 'CONTACT URI HOST PORT' =>  { '1.4.0 to 3.0.1' => 'sip.contact.port', },
 'TRIGGER-CONSENT' =>  { '1.2.0 to 3.0.1' => 'sip.Trigger-Consent', },
 'INVALID SIP VIA SENT-BY-PORT' =>  { '2.4.0 to 3.0.1' => 'sip.Via.sent-by.port.invalid', },
 'SERVER' =>  { '1.0.0 to 3.0.1' => 'sip.Server', },
 'EXPERT INFO' =>  { '1.12.0 to 2.0.16' => 'sip.response.unusual', },
 'SIP TO ADDRESS USER PART' =>  { '1.2.0 to 3.0.1' => 'sip.to.user', },
 'ROUTE' =>  { '1.0.0 to 3.0.1' => 'sip.Route', },
 'FEATURE-CAPS' =>  { '1.10.0 to 3.0.1' => 'sip.feature_caps', },
 'SERVICE-ROUTE HOST PART' =>  { '2.0.0 to 3.0.1' => 'sip.Service-Route.host', },
 'P-DCS-OSPS' =>  { '1.0.0 to 3.0.1' => 'sip.P-DCS-OSPS', },
 'PROXY-AUTHORIZATION' =>  { '1.0.0 to 3.0.1' => 'sip.Proxy-Authorization', },
 'SERVICE-ROUTE USERINFO' =>  { '2.0.0 to 3.0.1' => 'sip.Service-Route.user', },
 'REQUEST FRAME' =>  { '1.2.0 to 3.0.1' => 'sip.response-request', },
 'P-PROFILE-KEY' =>  { '1.0.0 to 3.0.1' => 'sip.P-Profile-Key', },
 'CAUSE' =>  { '2.4.0 to 3.0.1' => 'sip.reason_cause_other', '2.0.0 to 2.2.17' => 'sip.reason_cause', },
 'AUTHENTICATION-INFO' =>  { '1.0.0 to 3.0.1' => 'sip.Authentication-Info', },
 'P-CHARGING-FUNCTION-ADDRESSES' =>  { '1.0.0 to 3.0.1' => 'sip.P-Charging-Function-Addresses', },
 'PATH' =>  { '1.0.0 to 3.0.1' => 'sip.Path', },
 'REASON' =>  { '1.0.0 to 3.0.1' => 'sip.Reason', },
 'P-DCS-REDIRECT' =>  { '1.0.0 to 3.0.1' => 'sip.P-DCS-Redirect', },
 'SERVICE-ROUTE URI PARAMETER' =>  { '2.0.0 to 3.0.1' => 'sip.Service-Route.param', },
 'SIP FROM ADDRESS USER PART' =>  { '1.2.0 to 3.0.1' => 'sip.from.user', },
 'SIP CONTACT ADDRESS' =>  { '1.0.0 to 1.2.18' => 'sip.contact.addr', },
); 
1;