#!/usr/bin/expect

#exp_internal -f  expect.log 0
set systemTime [clock seconds]
set time [clock format $systemTime -format %a_%b_%d_%Y_%H_%M_%S]
append newfile "~/ats_repos/lib/perl/SonusQA/PSX/Logs/psxSlaveInstall_10_03_${time}.log"

log_file -noappend "$newfile";

set send_slow {1 0.02}

set slaveip [lindex $argv 0]
set mastername [lindex $argv 1]
set masterip [lindex $argv 2]

spawn bash -c "ssh-keygen -f ~/.ssh/known_hosts -R $slaveip"
#spawn bash -c "ssh-keygen -R $slaveip"

sleep 10

set timeout 20 

spawn ssh -o ServerAliveInterval=60  -o StrictHostKeyChecking=no ssuser@$slaveip;

expect -re ".*password:"
send -s "ssuser\r"

sleep 5

expect -re ".*password for ssuser:"
send -s "ssuser\r"

set timeout 300

expect {
     -re "Do you want to change the password for ssuser.*" { sleep 5; send -s "n\r"}
     timeout { send_user "Do you want to change the password for ssuser\n"; exit 0 }
       }

expect {
    -re "Do you want to change the password for oracle.*" { sleep 5; send -s "n\r" ; sleep 5}
    timeout { send_user "Do you want to change the password for oracle\n"; exit 0 }
       }

expect {
    -re "Do you want to change the password for root.*" { sleep 5; send -s "n\r"; sleep 5 }
    timeout { send_user "Do you want to change the password for root\n"; exit 0 }
       }

expect {
    -re "Do you want to change the password for admin.*" { sleep 5; send -s "n\r"; sleep 5 }
    timeout { send_user "Do you want to change the password for admin\n"; exit 0 }
       }

expect {
    -re "Is this PSX a master or slave.*"  { sleep 5; send -s "S\r"; sleep 5 }
    timeout { send_user "Did not find input - Is this PSX a master or slave \n"; exit 0 }
      }

expect {
    -re "Master host name.*"  { sleep 5; send -s "$mastername\r"; sleep 5 } 
    timeout { send_user "Did not find input - Master host name\n"; exit 0 }
      }

expect {
        -re "IP address of the master system.*" { sleep 5; send -s "$masterip\r"; sleep 5 } 
        timeout { send_user "Did not find input - IP address of the master system\n"; exit 0 }
      }


set timeout 3600

expect { 

    -re "Master.*or.*Slave.*database.*S" {sleep 5}

    timeout { send_user "pattern failed\n"; }
       }

sleep 5
    
expect {
        -re "Please confirm values.*" { sleep 5; send -s "Y\r"; }
        timeout { send_user "Did not find input - Please confirm values\n"; }
      }

sleep 300

expect -re ".*>"


#start softswitch

# su - oracle

# dbsync

#validate o/p

exit 1
