#!/usr/local/bin/perl
#
# File automatically generated by 'camBuilder.pl', do not edit!
#


$recordTable{START}[1][0] = "Record Type";
$recordTable{START}[2][0] = "Gateway Name";
$recordTable{START}[3][0] = "Accounting ID";
$recordTable{START}[4][0] = "Start Time (system ticks)";
$recordTable{START}[5][0] = "Node Time Zone";
$recordTable{START}[6][0] = "Start Time (MM/DD/YYYY)";
$recordTable{START}[7][0] = "Start Time (HH/MM/SS.s)";
$recordTable{START}[8][0] = "Ticks from Setup Msg to Policy Response";
$recordTable{START}[9][0] = "Ticks from Setup Msg to Alert/Proc/Prog";
$recordTable{START}[10][0] = "Ticks from Setup Msg to Service Est";
$recordTable{START}[11][0] = "Service Delivered";
$recordTable{START}[12][0] = "Call Direction";
$recordTable{START}[13][0] = "Service Provider";
$recordTable{START}[14][0] = "Transit Network Selection Code (TNS)";
$recordTable{START}[15][0] = "Calling Number";
$recordTable{START}[16][0] = "Called Number";
$recordTable{START}[17][0] = "Extra Called Address Digits";
$recordTable{START}[18][0] = "Number of Called Num Translations";
$recordTable{START}[19][0] = "Called Number Before Translation #1";
$recordTable{START}[20][0] = "Translation Type #1";
$recordTable{START}[21][0] = "Called Number Before Translation #2";
$recordTable{START}[22][0] = "Translation Type #2";
$recordTable{START}[23][0] = "Billing Number";
$recordTable{START}[24][0] = "Route Label";
$recordTable{START}[25][0] = "Route Attempt Number";
$recordTable{START}[26][0] = "Route Selected";
$recordTable{START}[27][0] = "Egress Local Signaling IP Address";
$recordTable{START}[28][0] = "Egress Remote Signaling IP Address";
$recordTable{START}[29][0] = "Ingress Trunk Group Name";
$recordTable{START}[30][0] = "Ingress PSTN Circuit End Point";
$recordTable{START}[31][0] = "Ingress IP Circuit End Point";
$recordTable{START}[32][0] = "Egress PSTN Circuit End Point";
$recordTable{START}[33][0] = "Egress IP Circuit End Point";
$recordTable{START}[34][0] = "Originating Line Information (OLIP)";
$recordTable{START}[35][0] = "Jurisdiction Information Parameter (JIP)";
$recordTable{START}[36][0] = "Carrier Code";
$recordTable{START}[37][0] = "Call Group ID";
$recordTable{START}[38][0] = "Ticks from Setup Msg to Rx of EXM";
$recordTable{START}[39][0] = "Ticks from Setup Msg to Generation of EXM";
$recordTable{START}[40][0] = "Calling Party Nature of Address";
$recordTable{START}[41][0] = "Called Party Nature of Address";
$recordTable{START}[42][0] = "Ingress Protocol Variant Specific Data";
$recordTable{START}[43][0] = "Ingress Signaling Type";
$recordTable{START}[44][0] = "Egress Signaling Type";
$recordTable{START}[45][0] = "Ingress Far End Switch Type";
$recordTable{START}[46][0] = "Egress Far End Switch Type";
$recordTable{START}[47][0] = "Carrier Code of Carrier who Owns iTG Far End";
$recordTable{START}[48][0] = "Carrier Code of Carrier who Owns eTG Far End";
$recordTable{START}[49][0] = "Calling Party Category";
$recordTable{START}[50][0] = "Dialed Number";
$recordTable{START}[51][0] = "Carrier Selection Information";
$recordTable{START}[52][0] = "Called Number Numbering Plan";
$recordTable{START}[53][0] = "Generic Address Parameter";
$recordTable{START}[54][0] = "Egress Trunk Group Name";
$recordTable{START}[55][0] = "Egress Protocol Variant Specific Data";
$recordTable{START}[56][0] = "Incoming Calling Number";
$recordTable{START}[57][0] = "AMA Call Type";
$recordTable{START}[58][0] = "Message Billing Indicator (MBI)";
$recordTable{START}[59][0] = "LATA";
$recordTable{START}[60][0] = "Route Index Used";
$recordTable{START}[61][0] = "Calling Party Presentation Restriction";
$recordTable{START}[62][0] = "Incoming ISUP Charge Number";
$recordTable{START}[63][0] = "Incoming ISUP Nature Of Address";
$recordTable{START}[64][0] = "Dialed Number Nature of Address";
$recordTable{START}[65][0] = "Global Call ID (GCID)";
$recordTable{START}[66][0] = "Charge Flag";
$recordTable{START}[67][0] = "AMA slp ID";
$recordTable{START}[68][0] = "AMA BAF Module";
$recordTable{START}[69][0] = "AMA Set Hex AB Indication";
$recordTable{START}[70][0] = "Service Feature ID";
$recordTable{START}[71][0] = "FE Parameter";
$recordTable{START}[72][0] = "Satellite Indicator";
$recordTable{START}[73][0] = "PSX Billing Info";
$recordTable{START}[74][0] = "Originating TDM Trunk Group Type";
$recordTable{START}[75][0] = "Terminating TDM Trunk Group Type";
$recordTable{START}[76][0] = "Ingress Trunk Member Number";
$recordTable{START}[77][0] = "Egress Trunk Group ID";
$recordTable{START}[78][0] = "Egress Switch ID";
$recordTable{START}[79][0] = "Ingress Local ATM Address";
$recordTable{START}[80][0] = "Ingress Remote ATM Address";
$recordTable{START}[81][0] = "Egress Local ATM Address";
$recordTable{START}[82][0] = "Egress Remote ATM Address";
$recordTable{START}[83][0] = "PSX Call Type";
$recordTable{START}[84][0] = "Outgoing Route Trunk Group ID";
$recordTable{START}[85][0] = "Outgoing Route Message ID";
$recordTable{START}[86][0] = "Incoming Route ID";
$recordTable{START}[87][0] = "Calling Name";
$recordTable{START}[88][0] = "Calling Name Type";
$recordTable{START}[89][0] = "Incoming Calling Party Numbering Plan";
$recordTable{START}[90][0] = "Outgoing Calling Party Numbering Plan";
$recordTable{START}[91][0] = "Calling Party Business Group ID";
$recordTable{START}[92][0] = "Called Party Business Group ID";
$recordTable{START}[93][0] = "Calling Party PPDN";
$recordTable{START}[94][0] = "Ticks from Setup Msg to Last Route Attempt";
$recordTable{START}[95][0] = "Billing Number Nature of Address";
$recordTable{START}[96][0] = "Incoming Calling Number Nature of Address";
$recordTable{START}[97][0] = "Egress Trunk Member Number";
$recordTable{START}[98][0] = "Selected Route Type";
$recordTable{START}[99][0] = "Cumulative Route Index";
$recordTable{START}[100][0] = "ISDN PRI Calling Party Subaddress";
$recordTable{START}[101][0] = "Outgoing Trunk Group Number in EXM";
$recordTable{START}[102][0] = "Ingress Local Signaling IP Address";
$recordTable{START}[103][0] = "Ingress Remote Signaling IP Address";
$recordTable{START}[104][0] = "Record Sequence Number";
$recordTable{START}[105][0] = "Transmission Medium Requirement";
$recordTable{START}[106][0] = "Information Transfer Rate";
$recordTable{START}[107][0] = "USI User Info Layer 1";
$recordTable{START}[108][0] = "Unrecognized Raw ISUP Calling Party Category";
$recordTable{START}[109][0] = "FSD: Egress Release Link Trunking";
$recordTable{START}[110][0] = "FSD: Two B-Channel Transfer";
$recordTable{START}[111][0] = "Calling Party Business Unit";
$recordTable{START}[112][0] = "Called Party Business Unit";
$recordTable{START}[113][0] = "FSD: Redirecting";
$recordTable{START}[114][0] = "FSD: Ingress Release Link Trunking";
$recordTable{START}[115][0] = "PSX ID";
$recordTable{START}[116][0] = "PSX Congestion Level";
$recordTable{START}[117][0] = "PSX Processing Time (milliseconds)";
$recordTable{START}[118][0] = "Script Name";
$recordTable{START}[119][0] = "Ingress External Accounting Data";
$recordTable{START}[120][0] = "Egress External Accounting Data";
$recordTable{START}[121][0] = "Answer Supervision Type ";
$recordTable{START}[122][0] = "Ingress Sip Refer or Sip Replaces Feature Specific Data";
$recordTable{START}[123][0] = "Egress Sip Refer or Sip Replaces Feature Specific Data";
$recordTable{START}[124][0] = "Network Transfers Feature Specific Data";
$recordTable{START}[125][0] = "Call Condition";
$recordTable{START}[126][0] = "Toll Indicator ";
$recordTable{START}[127][0] = "Generic Number ( Number )";
$recordTable{START}[128][0] = "Generic Number Presentation Restriction Indicator";
$recordTable{START}[129][0] = "Generic Number Numbering Plan";
$recordTable{START}[130][0] = "Generic Number Nature of Address";
$recordTable{START}[131][0] = "Generic Number Type";
$recordTable{START}[132][0] = "Originating Trunk Type";
$recordTable{START}[133][0] = "Terminating Trunk Type";
$recordTable{START}[134][0] = "VPN Calling Public Presence Number";
$recordTable{START}[135][0] = "VPN Calling Private Presence Number";
$recordTable{START}[136][0] = "External Furnish Charging Info";
$recordTable{START}[137][0] = "Announcement Id  ";
$recordTable{START}[138][0] = "Network Data - Source Information";
$recordTable{START}[139][0] = "Network Data - Partition ID";
$recordTable{START}[140][0] = "Network Data - Network ID";
$recordTable{START}[141][0] = "Network Data - NCOS";
$recordTable{START}[142][0] = "ISDN access Indicator";
$recordTable{START}[143][0] = "Network Call Reference - Call Identity";
$recordTable{START}[144][0] = "Network Call Reference - Signaling Point Code";
$recordTable{START}[145][0] = "Ingress MIME Protocol Variant Specific Data";
$recordTable{START}[146][0] = "Egress MIME Protocol Variant Specific Data";
$recordTable{START}[147][0] = "Video Data - Video Bandwidth, Video Call Duration,Ingress/Egress IP video Endpoint, Video Codec";
$recordTable{START}[148][0] = "SVS Customer";
$recordTable{START}[149][0] = "SVS Vendor - Deprecated in 7.2.2 as part of Pcr1624";
$recordTable{START}[150][0] = "Remote GSX Billing Indicator (PCR1216 - GSX 6.4 for KDDI special V3)";
$recordTable{START}[151][0] = "Call To Test PSX";
$recordTable{START}[152][0] = "Psx Overlap Route Requests";
$recordTable{START}[153][0] = "Call Setup Delay";
$recordTable{START}[153][1] = "Request Latency (msec)";
$recordTable{START}[153][2] = "Downstream Latency (msec)";
$recordTable{START}[153][3] = "Response Latency (msec)";
$recordTable{START}[153][4] = "Upstream Latency (msec)";
$recordTable{START}[154][0] = "Overload Status";
$recordTable{START}[155][0] = "Ingress BICC Info ";
$recordTable{START}[155][1] = "Circuit Identification Code ";
$recordTable{START}[155][2] = "Local Point Code";
$recordTable{START}[155][3] = "Remote Point Code ";
$recordTable{START}[155][4] = "Bearer Setup Mode";
$recordTable{START}[156][0] = "Egress BICC Info ";
$recordTable{START}[156][1] = "Circuit Identification Code ";
$recordTable{START}[156][2] = "Local Point Code";
$recordTable{START}[156][3] = "Remote Point Code ";
$recordTable{START}[156][4] = "Bearer Setup Mode";
$recordTable{START}[157][0] = "MLPP Precedence Level";
$recordTable{START}[158][0] = "MSRP Service Type";
$recordTable{START}[159][0] = "Special Routing Information";
$recordTable{START}[160][0] = "Customer or Carrier Identifier";
$recordTable{START}[161][0] = "Service Type Identifier";
$recordTable{START}[162][0] = "Special Handling Information";
$recordTable{START}[163][0] = "Service Type Identifier";
$recordTable{START}[164][0] = "oniStr";
$recordTable{START}[165][0] = "suppressONI";
$recordTable{START}[166][0] = "GCR Global Charge Reference";
$recordTable{START}[167][0] = "Ingress SIP Peer Call Limit Exceeded  ";
$recordTable{START}[168][0] = "Ingress IPTG Call Limit Exceeded  ";
$recordTable{START}[169][0] = "Ingress IPTG BW Limit Exceeded ";
$recordTable{START}[170][0] = "Egress SIP Peer Call Limit Exceeded ";
$recordTable{START}[171][0] = "Egress IPTG Call Limit Exceeded";
$recordTable{START}[172][0] = "Egress IPTG BW Limit Exceeded ";
$recordTable{START}[173][0] = "PSX Name";
$recordTable{START}[174][0] = "No.of PSX tried ";
$recordTable{START}[175][0] = "Final Route Label";
$recordTable{START}[176][0] = "MTA Information";
$recordTable{START}[176][1] = "Origination Primary";
$recordTable{START}[176][2] = "Origination Secondary";
$recordTable{START}[176][3] = "Destination Primary";
$recordTable{START}[176][4] = "Destination Secondary";

$recordTable{STOP}[1][0] = "Record Type";
$recordTable{STOP}[2][0] = "Gateway Name";
$recordTable{STOP}[3][0] = "Accounting ID";
$recordTable{STOP}[4][0] = "Start Time (system ticks)";
$recordTable{STOP}[5][0] = "Node Time Zone";
$recordTable{STOP}[6][0] = "Start Time (MM/DD/YYYY)";
$recordTable{STOP}[7][0] = "Start Time (HH/MM/SS.s)";
$recordTable{STOP}[8][0] = "Ticks from Setup Msg to Policy Response";
$recordTable{STOP}[9][0] = "Ticks from Setup Msg to Alert/Proc/Prog";
$recordTable{STOP}[10][0] = "Ticks from Setup Msg to Service Est";
$recordTable{STOP}[11][0] = "Disconnect Time (MM/DD/YYYY)";
$recordTable{STOP}[12][0] = "Disconnect Time (HH:MM:SS.s)";
$recordTable{STOP}[13][0] = "Ticks from Disconnect to Call Termination";
$recordTable{STOP}[14][0] = "Call Service Duration";
$recordTable{STOP}[15][0] = "Call Disconnect Reason";
$recordTable{STOP}[16][0] = "Service Delivered";
$recordTable{STOP}[17][0] = "Call Direction";
$recordTable{STOP}[18][0] = "Service Provider";
$recordTable{STOP}[19][0] = "Transit Network Selection Code (TNS)";
$recordTable{STOP}[20][0] = "Calling Number";
$recordTable{STOP}[21][0] = "Called Number";
$recordTable{STOP}[22][0] = "Extra Called Address Digits";
$recordTable{STOP}[23][0] = "Number of Called Num Translations";
$recordTable{STOP}[24][0] = "Called Number Before Translation #1";
$recordTable{STOP}[25][0] = "Translation Type #1";
$recordTable{STOP}[26][0] = "Called Number Before Translation #2";
$recordTable{STOP}[27][0] = "Translation Type #2";
$recordTable{STOP}[28][0] = "Billing Number";
$recordTable{STOP}[29][0] = "Route Label";
$recordTable{STOP}[30][0] = "Route Attempt Number";
$recordTable{STOP}[31][0] = "Route Selected";
$recordTable{STOP}[32][0] = "Egress Local Signaling IP Address";
$recordTable{STOP}[33][0] = "Egress Remote Signaling IP Address";
$recordTable{STOP}[34][0] = "Ingress Trunk Group Name";
$recordTable{STOP}[35][0] = "Ingress PSTN Circuit End Point";
$recordTable{STOP}[36][0] = "Ingress IP Circuit End Point";
$recordTable{STOP}[37][0] = "Egress PSTN Circuit End Point";
$recordTable{STOP}[38][0] = "Egress IP Circuit End Point";
$recordTable{STOP}[39][0] = "Ingress Number of Audio Bytes Sent";
$recordTable{STOP}[40][0] = "Ingress Number of Audio Packets Sent";
$recordTable{STOP}[41][0] = "Ingress Number of Audio Bytes Received";
$recordTable{STOP}[42][0] = "Ingress Number of Audio Packets Received";
$recordTable{STOP}[43][0] = "Originating Line Information (OLIP)";
$recordTable{STOP}[44][0] = "Jurisdiction Information Parameter (JIP)";
$recordTable{STOP}[45][0] = "Carrier Code";
$recordTable{STOP}[46][0] = "Call Group ID";
$recordTable{STOP}[47][0] = "Script Log Data";
$recordTable{STOP}[48][0] = "Ticks from Setup Msg to Rx of EXM";
$recordTable{STOP}[49][0] = "Ticks from Setup Msg to Generation of EXM";
$recordTable{STOP}[50][0] = "Calling Party Nature of Address";
$recordTable{STOP}[51][0] = "Called Party Nature of Address";
$recordTable{STOP}[52][0] = "Ingress Protocol Variant Specific Data";
$recordTable{STOP}[53][0] = "Ingress Signaling Type";
$recordTable{STOP}[54][0] = "Egress Signaling Type";
$recordTable{STOP}[55][0] = "Ingress Far End Switch Type";
$recordTable{STOP}[56][0] = "Egress Far End Switch Type";
$recordTable{STOP}[57][0] = "Carrier Code of Carrier who Owns iTG Far End";
$recordTable{STOP}[58][0] = "Carrier Code of Carrier who Owns eTG Far End";
$recordTable{STOP}[59][0] = "Calling Party Category";
$recordTable{STOP}[60][0] = "Dialed Number";
$recordTable{STOP}[61][0] = "Carrier Selection Information";
$recordTable{STOP}[62][0] = "Called Number Numbering Plan";
$recordTable{STOP}[63][0] = "Generic Address Parameter";
$recordTable{STOP}[64][0] = "Disconnect Initiator";
$recordTable{STOP}[65][0] = "Ingress Number of Packets Recorded as Lost";
$recordTable{STOP}[66][0] = "Ingress Interarrival Packet Jitter";
$recordTable{STOP}[67][0] = "Ingress Last Measurement for Latency";
$recordTable{STOP}[68][0] = "Egress Trunk Group Name";
$recordTable{STOP}[69][0] = "Egress Protocol Variant Specific Data";
$recordTable{STOP}[70][0] = "Incoming Calling Number";
$recordTable{STOP}[71][0] = "AMA Call Type";
$recordTable{STOP}[72][0] = "Message Billing Indicator (MBI)";
$recordTable{STOP}[73][0] = "LATA";
$recordTable{STOP}[74][0] = "Route Index Used";
$recordTable{STOP}[75][0] = "Calling Party Presentation Restriction";
$recordTable{STOP}[76][0] = "Incoming ISUP Charge Number";
$recordTable{STOP}[77][0] = "Incoming ISUP Nature Of Address";
$recordTable{STOP}[78][0] = "Dialed Number Nature of Address";
$recordTable{STOP}[79][0] = "Ingress Codec Info";
$recordTable{STOP}[80][0] = "Egress Codec Info";
$recordTable{STOP}[81][0] = "Ingress RTP Packetization Time";
$recordTable{STOP}[82][0] = "Global Call ID (GCID)";
$recordTable{STOP}[83][0] = "Originator Echo Cancellation";
$recordTable{STOP}[84][0] = "Terminator Echo Cancellation";
$recordTable{STOP}[85][0] = "Charge Flag";
$recordTable{STOP}[86][0] = "AMA slp ID";
$recordTable{STOP}[87][0] = "AMA BAF Module";
$recordTable{STOP}[88][0] = "AMA Set Hex AB Indication";
$recordTable{STOP}[89][0] = "Service Feature ID";
$recordTable{STOP}[90][0] = "FE Parameter";
$recordTable{STOP}[91][0] = "Satellite Indicator";
$recordTable{STOP}[92][0] = "PSX Billing Info";
$recordTable{STOP}[93][0] = "Originating TDM Trunk Group Type";
$recordTable{STOP}[94][0] = "Terminating TDM Trunk Group Type";
$recordTable{STOP}[95][0] = "Ingress Trunk Member Number";
$recordTable{STOP}[96][0] = "Egress Trunk Group ID";
$recordTable{STOP}[97][0] = "Egress Switch ID";
$recordTable{STOP}[98][0] = "Ingress Local ATM Address";
$recordTable{STOP}[99][0] = "Ingress Remote ATM Address";
$recordTable{STOP}[100][0] = "Egress Local ATM Address";
$recordTable{STOP}[101][0] = "Egress Remote ATM Address";
$recordTable{STOP}[102][0] = "PSX Call Type";
$recordTable{STOP}[103][0] = "Outgoing Route Trunk Group ID";
$recordTable{STOP}[104][0] = "Outgoing Route Message ID";
$recordTable{STOP}[105][0] = "Incoming Route ID";
$recordTable{STOP}[106][0] = "Calling Name";
$recordTable{STOP}[107][0] = "Calling Name Type";
$recordTable{STOP}[108][0] = "Incoming Calling Party Numbering Plan";
$recordTable{STOP}[109][0] = "Outgoing Calling Party Numbering Plan";
$recordTable{STOP}[110][0] = "Calling Party Business Group ID";
$recordTable{STOP}[111][0] = "Called Party Business Group ID";
$recordTable{STOP}[112][0] = "Calling Party PPDN";
$recordTable{STOP}[113][0] = "Ticks from Setup Msg to Last Route Attempt";
$recordTable{STOP}[114][0] = "Billing Number Nature of Address";
$recordTable{STOP}[115][0] = "Incoming Calling Number Nature of Address";
$recordTable{STOP}[116][0] = "Egress Trunk Member Number";
$recordTable{STOP}[117][0] = "Selected Route Type";
$recordTable{STOP}[118][0] = "Telcordia Long Duration Record Type";
$recordTable{STOP}[119][0] = "Ticks From Previous Record";
$recordTable{STOP}[120][0] = "Cumulative Route Index";
$recordTable{STOP}[121][0] = "Call Disconnect Reason Sent to Ingress";
$recordTable{STOP}[122][0] = "Call Disconnect Reason Sent to Egress";
$recordTable{STOP}[123][0] = "ISDN PRI Calling Party Subaddress";
$recordTable{STOP}[124][0] = "Outgoing Trunk Group Number in EXM";
$recordTable{STOP}[125][0] = "Ingress Local Signaling IP Address";
$recordTable{STOP}[126][0] = "Ingress Remote Signaling IP Address";
$recordTable{STOP}[127][0] = "Record Sequence Number";
$recordTable{STOP}[128][0] = "Transmission Medium Requirement";
$recordTable{STOP}[129][0] = "Information Transfer Rate";
$recordTable{STOP}[130][0] = "USI User Info Layer 1";
$recordTable{STOP}[131][0] = "Unrecognized Raw ISUP Calling Party Category";
$recordTable{STOP}[132][0] = "FSD: Egress Release Link Trunking";
$recordTable{STOP}[133][0] = "FSD: Two B-Channel Transfer";
$recordTable{STOP}[134][0] = "Calling Party Business Unit";
$recordTable{STOP}[135][0] = "Called Party Business Unit";
$recordTable{STOP}[136][0] = "FSD: Redirecting";
$recordTable{STOP}[137][0] = "FSD: Ingress Release Link Trunking";
$recordTable{STOP}[138][0] = "PSX Index";
$recordTable{STOP}[139][0] = "PSX Congestion Level";
$recordTable{STOP}[140][0] = "PSX Processing Time (milliseconds)";
$recordTable{STOP}[141][0] = "Script Name";
$recordTable{STOP}[142][0] = "Ingress External Accounting Data";
$recordTable{STOP}[143][0] = "Egress External Accounting Data";
$recordTable{STOP}[144][0] = "Egress RTP Packetization Time";
$recordTable{STOP}[145][0] = "Egress Number of Audio Bytes Sent";
$recordTable{STOP}[146][0] = "Egress Number of Audio Packets Sent";
$recordTable{STOP}[147][0] = "Egress Number of Audio Bytes Received";
$recordTable{STOP}[148][0] = "Egress Number of Audio Packets Received";
$recordTable{STOP}[149][0] = "Egress Number of Packets Recorded as Lost";
$recordTable{STOP}[150][0] = "Egress Interarrival Packet Jitter";
$recordTable{STOP}[151][0] = "Egress Last Measurement for Latency";
$recordTable{STOP}[152][0] = "Ingress Maximum Packet Outage";
$recordTable{STOP}[153][0] = "Egress Maximum Packet Outage";
$recordTable{STOP}[154][0] = "Ingress Packet Playout Buffer Quality";
$recordTable{STOP}[155][0] = "Egress Packet Playout Buffer Quality";
$recordTable{STOP}[156][0] = "Answer Supervision Type";
$recordTable{STOP}[157][0] = "Ingress Sip Refer or Sip Replaces Feature Specific Data";
$recordTable{STOP}[158][0] = "Egress Sip Refer or Sip Replaces Feature Specific Data";
$recordTable{STOP}[159][0] = "Network Transfers Feature Specific Data";
$recordTable{STOP}[160][0] = "Call Condition";
$recordTable{STOP}[161][0] = "Toll Indicator";
$recordTable{STOP}[162][0] = "Generic Number ( Number )";
$recordTable{STOP}[163][0] = "Generic Number Presentation Restriction Indicator";
$recordTable{STOP}[164][0] = "Generic Number Numbering Plan";
$recordTable{STOP}[165][0] = "Generic Number Nature of Address";
$recordTable{STOP}[166][0] = "Generic Number Type";
$recordTable{STOP}[167][0] = "Originating Trunk Type";
$recordTable{STOP}[168][0] = "Terminating Trunk Type";
$recordTable{STOP}[169][0] = "Remote GSX Billing Indicator";
$recordTable{STOP}[170][0] = "VPN Calling Private Presence Number";
$recordTable{STOP}[171][0] = "VPN Calling Public Presence Number";
$recordTable{STOP}[172][0] = "External Furnish Charging Info";
$recordTable{STOP}[173][0] = "Ingress Policing Discards";
$recordTable{STOP}[174][0] = "Egress Policing Discards";
$recordTable{STOP}[175][0] = "Announcement Id  ";
$recordTable{STOP}[176][0] = "Network Data - Source Information";
$recordTable{STOP}[177][0] = "Network Data - Partition ID";
$recordTable{STOP}[178][0] = "Network Data - Network ID";
$recordTable{STOP}[179][0] = "Network Data - NCOS";
$recordTable{STOP}[180][0] = "Ingress SRTP (Secure RTP/RTCP)";
$recordTable{STOP}[181][0] = "Egress SRTP (Secure RTP/RTCP)";
$recordTable{STOP}[182][0] = "ISDN access Indicator";
$recordTable{STOP}[183][0] = "Call Disconnect Location";
$recordTable{STOP}[184][0] = "Call Disconnect Location Transmitted to Ingress";
$recordTable{STOP}[185][0] = "Call Disconnect Location Transmitted to Egress";
$recordTable{STOP}[186][0] = "Network Call Reference - Call Identity";
$recordTable{STOP}[187][0] = "Network Call Reference - Signaling Point Code";
$recordTable{STOP}[188][0] = "Ingress MIME Protocol Variant Specific Data";
$recordTable{STOP}[189][0] = "Egress MIME Protocol Variant Specific Data";
$recordTable{STOP}[190][0] = "Modem Tone Type";
$recordTable{STOP}[191][0] = "Modem Tone Signal Level ";
$recordTable{STOP}[192][0] = "Video Data - Video Bandwidth, Video Call Duration, Ingress/Egress IP Video End Point, Video Codec";
$recordTable{STOP}[193][0] = "Video Statistics - Ingress/Egress Video Statistics.";
$recordTable{STOP}[194][0] = "SVS Customer";
$recordTable{STOP}[195][0] = "SVS Vendor - Deprecated in 7.2.2 as part of Pcr1624";
$recordTable{STOP}[196][0] = "Call To Test PSX";
$recordTable{STOP}[197][0] = "Psx Overlap Route Requests";
$recordTable{STOP}[198][0] = "Call Setup Delay";
$recordTable{STOP}[198][1] = "Request Latency (msec)";
$recordTable{STOP}[198][2] = "Downstream Latency (msec)";
$recordTable{STOP}[198][3] = "Response Latency (msec)";
$recordTable{STOP}[198][4] = "Upstream Latency (msec)";
$recordTable{STOP}[199][0] = "Overload Status";
$recordTable{STOP}[200][0] = "Ingress BiccInfo ";
$recordTable{STOP}[200][1] = "Circuit Identification Code ";
$recordTable{STOP}[200][2] = "Local Point Code";
$recordTable{STOP}[200][3] = "Remote Point Code ";
$recordTable{STOP}[200][4] = "Bearer Setup Mode";
$recordTable{STOP}[201][0] = "Egress Bicc Info";
$recordTable{STOP}[201][1] = "Circuit Identification Code ";
$recordTable{STOP}[201][2] = "Local Point Code";
$recordTable{STOP}[201][3] = "Remote Point Code ";
$recordTable{STOP}[201][4] = "Bearer Setup Mode";
$recordTable{STOP}[202][0] = "Ingress DSP Data Bitmap";
$recordTable{STOP}[203][0] = "Egress DSP Data Bitmap";
$recordTable{STOP}[204][0] = "Call Recorded Indicator";
$recordTable{STOP}[205][0] = "Call Recorded RTP Tx Ip Address ";
$recordTable{STOP}[206][0] = "Call Recorded RTP Tx Port Number";
$recordTable{STOP}[207][0] = "Call Recorded RTP Rv Ip Address ";
$recordTable{STOP}[208][0] = "Call Recorded RTP Rv Port Number";
$recordTable{STOP}[209][0] = "Mlpp Precedence Level";
$recordTable{STOP}[210][0] = "MSRP Service Type";
$recordTable{STOP}[211][0] = "Special Routing Information   ";
$recordTable{STOP}[212][0] = "Customer Or Carrier Identifier";
$recordTable{STOP}[213][0] = "Service Type Identifier";
$recordTable{STOP}[214][0] = "Special Handling Information";
$recordTable{STOP}[215][0] = "Service Type Identifier";
$recordTable{STOP}[216][0] = "Itx charge information";
$recordTable{STOP}[217][0] = "GCR Global charge reference";
$recordTable{STOP}[218][0] = "Ingress SIP Peer Call Limit Exceeded";
$recordTable{STOP}[219][0] = "Ingress IPTG Call Limit Exceeded  ";
$recordTable{STOP}[220][0] = "Ingress IPTG BW Limit Exceeded ";
$recordTable{STOP}[221][0] = "Egress SIP Peer Call Limit Exceeded ";
$recordTable{STOP}[222][0] = "Egress IPTG Call Limit Exceeded ";
$recordTable{STOP}[223][0] = "Egress IPTG BW Limit Exceeded";
$recordTable{STOP}[224][0] = "PSX Name";
$recordTable{STOP}[225][0] = "No.of PSX tried ";
$recordTable{STOP}[226][0] = "Reserved";
$recordTable{STOP}[227][0] = "Reserved";
$recordTable{STOP}[228][0] = "Reserved";
$recordTable{STOP}[229][0] = "Reserved";
$recordTable{STOP}[230][0] = "Reserved";
$recordTable{STOP}[231][0] = "Reserved";
$recordTable{STOP}[232][0] = "Reserved";
$recordTable{STOP}[233][0] = "Reserved";
$recordTable{STOP}[234][0] = "Reserved";
$recordTable{STOP}[235][0] = "Reserved";
$recordTable{STOP}[236][0] = "Final Route Label";
$recordTable{STOP}[237][0] = "MTA Information";
$recordTable{STOP}[237][1] = "Origination Primary";
$recordTable{STOP}[237][2] = "Origination Secondary";
$recordTable{STOP}[237][3] = "Destination Primary";
$recordTable{STOP}[237][4] = "Destination Secondary";
$recordTable{STOP}[238][0] = "VBR Common Billing Data";
$recordTable{STOP}[239][0] = "VBR Route Billing Data";

$recordTable{ATTEMPT}[1][0] = "Record Type";
$recordTable{ATTEMPT}[2][0] = "Gateway Name";
$recordTable{ATTEMPT}[3][0] = "Accounting ID";
$recordTable{ATTEMPT}[4][0] = "Start Time (system ticks)";
$recordTable{ATTEMPT}[5][0] = "Node Time Zone";
$recordTable{ATTEMPT}[6][0] = "Start Time (MM/DD/YYYY)";
$recordTable{ATTEMPT}[7][0] = "Start Time (HH/MM/SS.s)";
$recordTable{ATTEMPT}[8][0] = "Ticks from Setup Msg to Policy Response";
$recordTable{ATTEMPT}[9][0] = "Ticks from Setup Msg to Alert/Proc/Prog";
$recordTable{ATTEMPT}[10][0] = "Disconnect Time (HH:MM:SS.s)";
$recordTable{ATTEMPT}[11][0] = "Ticks from Disconnect to Call Termination";
$recordTable{ATTEMPT}[12][0] = "Call Disconnect Reason";
$recordTable{ATTEMPT}[13][0] = "Service Delivered";
$recordTable{ATTEMPT}[14][0] = "Call Direction";
$recordTable{ATTEMPT}[15][0] = "Service Provider";
$recordTable{ATTEMPT}[16][0] = "Transit Network Selection Code (TNS)";
$recordTable{ATTEMPT}[17][0] = "Calling Number";
$recordTable{ATTEMPT}[18][0] = "Called Number";
$recordTable{ATTEMPT}[19][0] = "Extra Called Address Digits";
$recordTable{ATTEMPT}[20][0] = "Number of Called Num Translations";
$recordTable{ATTEMPT}[21][0] = "Called Number Before Translation #1";
$recordTable{ATTEMPT}[22][0] = "Translation Type #1";
$recordTable{ATTEMPT}[23][0] = "Called Number Before Translation #2";
$recordTable{ATTEMPT}[24][0] = "Translation Type #2";
$recordTable{ATTEMPT}[25][0] = "Billing Number";
$recordTable{ATTEMPT}[26][0] = "Route Label";
$recordTable{ATTEMPT}[27][0] = "Route Attempt Number";
$recordTable{ATTEMPT}[28][0] = "Route Selected";
$recordTable{ATTEMPT}[29][0] = "Egress Local Signaling IP Address";
$recordTable{ATTEMPT}[30][0] = "Egress Remote Signaling IP Address";
$recordTable{ATTEMPT}[31][0] = "Ingress Trunk Group Name";
$recordTable{ATTEMPT}[32][0] = "Ingress PSTN Circuit End Point";
$recordTable{ATTEMPT}[33][0] = "Ingress IP Circuit End Point";
$recordTable{ATTEMPT}[34][0] = "Egress PSTN Circuit End Point";
$recordTable{ATTEMPT}[35][0] = "Egress IP Circuit End Point";
$recordTable{ATTEMPT}[36][0] = "Originating Line Information (OLIP)";
$recordTable{ATTEMPT}[37][0] = "Jurisdiction Information Parameter (JIP)";
$recordTable{ATTEMPT}[38][0] = "Carrier Code";
$recordTable{ATTEMPT}[39][0] = "Call Group ID";
$recordTable{ATTEMPT}[40][0] = "Script Log Data";
$recordTable{ATTEMPT}[41][0] = "Ticks from Setup Msg to Rx of EXM";
$recordTable{ATTEMPT}[42][0] = "Ticks from Setup Msg to Generation of EXM";
$recordTable{ATTEMPT}[43][0] = "Calling Party Nature of Address";
$recordTable{ATTEMPT}[44][0] = "Called Party Nature of Address";
$recordTable{ATTEMPT}[45][0] = "Ingress Protocol Variant Specific Data";
$recordTable{ATTEMPT}[46][0] = "Ingress Signaling Type";
$recordTable{ATTEMPT}[47][0] = "Egress Signaling Type";
$recordTable{ATTEMPT}[48][0] = "Ingress Far End Switch Type";
$recordTable{ATTEMPT}[49][0] = "Egress Far End Switch Type";
$recordTable{ATTEMPT}[50][0] = "Carrier Code of Carrier who Owns iTG Far End";
$recordTable{ATTEMPT}[51][0] = "Carrier Code of Carrier who Owns eTG Far End";
$recordTable{ATTEMPT}[52][0] = "Calling Party Category";
$recordTable{ATTEMPT}[53][0] = "Dialed Number";
$recordTable{ATTEMPT}[54][0] = "Carrier Selection Information";
$recordTable{ATTEMPT}[55][0] = "Called Number Numbering Plan";
$recordTable{ATTEMPT}[56][0] = "Generic Address Parameter";
$recordTable{ATTEMPT}[57][0] = "Disconnect Initiator";
$recordTable{ATTEMPT}[58][0] = "Egress Trunk Group Name";
$recordTable{ATTEMPT}[59][0] = "Egress Protocol Variant Specific Data";
$recordTable{ATTEMPT}[60][0] = "Incoming Calling Number";
$recordTable{ATTEMPT}[61][0] = "AMA Call Type";
$recordTable{ATTEMPT}[62][0] = "Message Billing Indicator (MBI)";
$recordTable{ATTEMPT}[63][0] = "LATA";
$recordTable{ATTEMPT}[64][0] = "Route Index Used";
$recordTable{ATTEMPT}[65][0] = "Calling Party Presentation Restriction";
$recordTable{ATTEMPT}[66][0] = "Incoming ISUP Charge Number";
$recordTable{ATTEMPT}[67][0] = "Incoming ISUP Nature Of Address";
$recordTable{ATTEMPT}[68][0] = "Dialed Number Nature of Address";
$recordTable{ATTEMPT}[69][0] = "Ingress Codec Info";
$recordTable{ATTEMPT}[70][0] = "Egress Codec Info";
$recordTable{ATTEMPT}[71][0] = "Ingress RTP Packetization Time";
$recordTable{ATTEMPT}[72][0] = "Global Call ID (GCID)";
$recordTable{ATTEMPT}[73][0] = "Terminated With Script Execution";
$recordTable{ATTEMPT}[74][0] = "Originator Echo Cancellation";
$recordTable{ATTEMPT}[75][0] = "Terminator Echo Cancellation";
$recordTable{ATTEMPT}[76][0] = "Charge Flag";
$recordTable{ATTEMPT}[77][0] = "AMA slp ID";
$recordTable{ATTEMPT}[78][0] = "AMA BAF Module";
$recordTable{ATTEMPT}[79][0] = "AMA Set Hex AB Indication";
$recordTable{ATTEMPT}[80][0] = "Service Feature ID";
$recordTable{ATTEMPT}[81][0] = "FE Parameter";
$recordTable{ATTEMPT}[82][0] = "Satellite Indicator";
$recordTable{ATTEMPT}[83][0] = "PSX Billing Info";
$recordTable{ATTEMPT}[84][0] = "Originating TDM Trunk Group Type";
$recordTable{ATTEMPT}[85][0] = "Terminating TDM Trunk Group Type";
$recordTable{ATTEMPT}[86][0] = "Ingress Trunk Member Number";
$recordTable{ATTEMPT}[87][0] = "Egress Trunk Group ID";
$recordTable{ATTEMPT}[88][0] = "Egress Switch ID";
$recordTable{ATTEMPT}[89][0] = "Ingress Local ATM Address";
$recordTable{ATTEMPT}[90][0] = "Ingress Remote ATM Address";
$recordTable{ATTEMPT}[91][0] = "Egress Local ATM Address";
$recordTable{ATTEMPT}[92][0] = "Egress Remote ATM Address";
$recordTable{ATTEMPT}[93][0] = "PSX Call Type";
$recordTable{ATTEMPT}[94][0] = "Outgoing Route Trunk Group ID";
$recordTable{ATTEMPT}[95][0] = "Outgoing Route Message ID";
$recordTable{ATTEMPT}[96][0] = "Incoming Route ID";
$recordTable{ATTEMPT}[97][0] = "Calling Name";
$recordTable{ATTEMPT}[98][0] = "Calling Name Type";
$recordTable{ATTEMPT}[99][0] = "Incoming Calling Party Numbering Plan";
$recordTable{ATTEMPT}[100][0] = "Outgoing Calling Party Numbering Plan";
$recordTable{ATTEMPT}[101][0] = "Calling Party Business Group ID";
$recordTable{ATTEMPT}[102][0] = "Called Party Business Group ID";
$recordTable{ATTEMPT}[103][0] = "Calling Party PPDN";
$recordTable{ATTEMPT}[104][0] = "Ticks from Setup Msg to Last Route Attempt";
$recordTable{ATTEMPT}[105][0] = "Disconnect Time (MM/DD/YYYY)";
$recordTable{ATTEMPT}[106][0] = "Billing Number Nature of Address";
$recordTable{ATTEMPT}[107][0] = "Incoming Calling Number Nature of Address";
$recordTable{ATTEMPT}[108][0] = "Egress Trunk Member Number";
$recordTable{ATTEMPT}[109][0] = "Selected Route Type";
$recordTable{ATTEMPT}[110][0] = "Cumulative Route Index";
$recordTable{ATTEMPT}[111][0] = "Call Disconnect Reason Sent to Ingress";
$recordTable{ATTEMPT}[112][0] = "Call Disconnect Reason Sent to Egress";
$recordTable{ATTEMPT}[113][0] = "ISDN PRI Calling Party Subaddress";
$recordTable{ATTEMPT}[114][0] = "Outgoing Trunk Group Number in EXM";
$recordTable{ATTEMPT}[115][0] = "Ingress Local Signaling IP Address";
$recordTable{ATTEMPT}[116][0] = "Ingress Remote Signaling IP Address";
$recordTable{ATTEMPT}[117][0] = "Record Sequence Number";
$recordTable{ATTEMPT}[118][0] = "Transmission Medium Requirement";
$recordTable{ATTEMPT}[119][0] = "Information Transfer Rate";
$recordTable{ATTEMPT}[120][0] = "USI User Info Layer 1";
$recordTable{ATTEMPT}[121][0] = "Unrecognized Raw ISUP Calling Party Category";
$recordTable{ATTEMPT}[122][0] = "FSD: Release Link Trunking";
$recordTable{ATTEMPT}[123][0] = "FSD: Two B-Channel Transfer";
$recordTable{ATTEMPT}[124][0] = "Calling Party Business Unit";
$recordTable{ATTEMPT}[125][0] = "Called Party Business Unit";
$recordTable{ATTEMPT}[126][0] = "FSD: Redirecting";
$recordTable{ATTEMPT}[127][0] = "FSD: Ingress Release Link Trunking";
$recordTable{ATTEMPT}[128][0] = "PSX Index";
$recordTable{ATTEMPT}[129][0] = "PSX Congestion Level";
$recordTable{ATTEMPT}[130][0] = "PSX Processing Time (milliseconds)";
$recordTable{ATTEMPT}[131][0] = "Script Name";
$recordTable{ATTEMPT}[132][0] = "Ingress External Accounting Data";
$recordTable{ATTEMPT}[133][0] = "Egress External Accounting Data";
$recordTable{ATTEMPT}[134][0] = "Egress RTP Packetization Time";
$recordTable{ATTEMPT}[135][0] = "Answer Supervision Type";
$recordTable{ATTEMPT}[136][0] = "Ingress Sip Refer & Replaces Feature Specific Data";
$recordTable{ATTEMPT}[137][0] = "Egress Sip Refer Feature Specific Data";
$recordTable{ATTEMPT}[138][0] = "Network Transfers Feature Specific Data";
$recordTable{ATTEMPT}[139][0] = "Call Condition";
$recordTable{ATTEMPT}[140][0] = "Toll Indicator";
$recordTable{ATTEMPT}[141][0] = "Generic Number ( Number )";
$recordTable{ATTEMPT}[142][0] = "Generic Number Presentation Restriction Indicator";
$recordTable{ATTEMPT}[143][0] = "Generic Number Numbering Plan";
$recordTable{ATTEMPT}[144][0] = "Generic Number Nature of Address";
$recordTable{ATTEMPT}[145][0] = "Generic Number Type";
$recordTable{ATTEMPT}[146][0] = "Final Attempt Indicator";
$recordTable{ATTEMPT}[147][0] = "Originating Trunk Type";
$recordTable{ATTEMPT}[148][0] = "Terminating Trunk Type";
$recordTable{ATTEMPT}[149][0] = "Remote GSX Billing Indicator";
$recordTable{ATTEMPT}[150][0] = "Extra Disconnect Reason";
$recordTable{ATTEMPT}[151][0] = "VPN Calling Private Presence Number";
$recordTable{ATTEMPT}[152][0] = "VPN Calling Public Presence Number";
$recordTable{ATTEMPT}[153][0] = "External Furnish Charging Info";
$recordTable{ATTEMPT}[154][0] = "Announcement Id  ";
$recordTable{ATTEMPT}[155][0] = "Network Data - Source Information";
$recordTable{ATTEMPT}[156][0] = "Network Data - Partition ID";
$recordTable{ATTEMPT}[157][0] = "Network Data - Network ID";
$recordTable{ATTEMPT}[158][0] = "Network Data - NCOS";
$recordTable{ATTEMPT}[159][0] = "ISDN access Indicator";
$recordTable{ATTEMPT}[160][0] = "Call Disconnect Location";
$recordTable{ATTEMPT}[161][0] = "Call Disconnect Location Transmitted to Ingress";
$recordTable{ATTEMPT}[162][0] = "Call Disconnect Location Transmitted to Egress";
$recordTable{ATTEMPT}[163][0] = "Network Call Reference - Call Identity";
$recordTable{ATTEMPT}[164][0] = "Network Call Reference - Signaling Point Code";
$recordTable{ATTEMPT}[165][0] = "Ingress MIME Protocol Variant Specific Data";
$recordTable{ATTEMPT}[166][0] = "Egress MIME Protocol Variant Specific Data";
$recordTable{ATTEMPT}[167][0] = "Video Data - Video Bandwidth, Video Call Duration,Ingress/Egress IP video Endpoint ";
$recordTable{ATTEMPT}[168][0] = "SVS Customer";
$recordTable{ATTEMPT}[169][0] = "SVS Vendor - Deprecated in 7.2.2 as part of Pcr1624";
$recordTable{ATTEMPT}[170][0] = "Call To Test PSX";
$recordTable{ATTEMPT}[171][0] = "Psx Overlap Route Requests";
$recordTable{ATTEMPT}[172][0] = "Call Setup Delay";
$recordTable{ATTEMPT}[172][1] = "Request Latency (msec)";
$recordTable{ATTEMPT}[172][2] = "Downstream Latency (msec)";
$recordTable{ATTEMPT}[172][3] = "Response Latency (msec)";
$recordTable{ATTEMPT}[172][4] = "Upstream Latency (msec)";
$recordTable{ATTEMPT}[173][0] = "Overload Status";
$recordTable{ATTEMPT}[174][0] = "Ingress Bicc Info";
$recordTable{ATTEMPT}[174][1] = "Circuit Identification Code ";
$recordTable{ATTEMPT}[174][2] = "Local Point Code";
$recordTable{ATTEMPT}[174][3] = "Remote Point Code ";
$recordTable{ATTEMPT}[174][4] = "Bearer Setup Mode";
$recordTable{ATTEMPT}[175][0] = "Egress Bicc Info";
$recordTable{ATTEMPT}[175][1] = "Circuit Identification Code ";
$recordTable{ATTEMPT}[175][2] = "Local Point Code";
$recordTable{ATTEMPT}[175][3] = "Remote Point Code ";
$recordTable{ATTEMPT}[175][4] = "Bearer Setup Mode";
$recordTable{ATTEMPT}[176][0] = "Mlpp Precedence Level";
$recordTable{ATTEMPT}[177][0] = "MSRP Service Type";
$recordTable{ATTEMPT}[178][0] = "Special Routing Information";
$recordTable{ATTEMPT}[179][0] = "Customer or Carrier Identifier     ";
$recordTable{ATTEMPT}[180][0] = "Service Type Identifier";
$recordTable{ATTEMPT}[181][0] = "Special Handling Information";
$recordTable{ATTEMPT}[182][0] = "Service Type Identifier";
$recordTable{ATTEMPT}[183][0] = "oniStr";
$recordTable{ATTEMPT}[184][0] = "suppressONI";
$recordTable{ATTEMPT}[185][0] = "GCR Global Charge Reference";
$recordTable{ATTEMPT}[186][0] = "3xx Contact Information";
$recordTable{ATTEMPT}[186][1] = "Contact1";
$recordTable{ATTEMPT}[186][2] = "Contact2";
$recordTable{ATTEMPT}[186][3] = "Contact3";
$recordTable{ATTEMPT}[186][4] = "Contact4";
$recordTable{ATTEMPT}[186][5] = "Contact5";
$recordTable{ATTEMPT}[186][6] = "Contact6";
$recordTable{ATTEMPT}[186][7] = "Contact7";
$recordTable{ATTEMPT}[186][8] = "Contact8";
$recordTable{ATTEMPT}[186][9] = "Contact9";
$recordTable{ATTEMPT}[186][10] = "Contact10";
$recordTable{ATTEMPT}[187][0] = "PSX Name";
$recordTable{ATTEMPT}[188][0] = "No.of PSX tried";
$recordTable{ATTEMPT}[189][0] = "Final Route Label";
$recordTable{ATTEMPT}[190][0] = "MTA Information";
$recordTable{ATTEMPT}[190][1] = "Origination Primary";
$recordTable{ATTEMPT}[190][2] = "Origination Secondary";
$recordTable{ATTEMPT}[190][3] = "Destination Primary";
$recordTable{ATTEMPT}[190][4] = "Destination Secondary";
$recordTable{ATTEMPT}[191][0] = "VBR Common Billing Data";
$recordTable{ATTEMPT}[192][0] = "VBR Route Billing Data";

$recordTable{INTERMEDIATE}[1][0] = "Record Type";
$recordTable{INTERMEDIATE}[2][0] = "Gateway Name";
$recordTable{INTERMEDIATE}[3][0] = "Accounting ID";
$recordTable{INTERMEDIATE}[4][0] = "Start Time (system ticks)";
$recordTable{INTERMEDIATE}[5][0] = "Node Time Zone";
$recordTable{INTERMEDIATE}[6][0] = "Start Time (MM/DD/YYYY)";
$recordTable{INTERMEDIATE}[7][0] = "Start Time (HH/MM/SS.s)";
$recordTable{INTERMEDIATE}[8][0] = "Ticks from Setup Msg to Policy Response";
$recordTable{INTERMEDIATE}[9][0] = "Ticks from Setup Msg to Service Est";
$recordTable{INTERMEDIATE}[10][0] = "Intermediate Time (MM/DD/YYYY)";
$recordTable{INTERMEDIATE}[11][0] = "Intermediate Time (HH:MM:SS.s)";
$recordTable{INTERMEDIATE}[12][0] = "Call Service Duration";
$recordTable{INTERMEDIATE}[13][0] = "Service Delivered";
$recordTable{INTERMEDIATE}[14][0] = "Call Direction";
$recordTable{INTERMEDIATE}[15][0] = "Service Provider";
$recordTable{INTERMEDIATE}[16][0] = "Transit Network Selection Code (TNS)";
$recordTable{INTERMEDIATE}[17][0] = "Calling Number";
$recordTable{INTERMEDIATE}[18][0] = "Called Number";
$recordTable{INTERMEDIATE}[19][0] = "Extra Called Address Digits";
$recordTable{INTERMEDIATE}[20][0] = "Number of Called Num Translations";
$recordTable{INTERMEDIATE}[21][0] = "Called Number Before Translation #1";
$recordTable{INTERMEDIATE}[22][0] = "Translation Type #1";
$recordTable{INTERMEDIATE}[23][0] = "Called Number Before Translation #2";
$recordTable{INTERMEDIATE}[24][0] = "Translation Type #2";
$recordTable{INTERMEDIATE}[25][0] = "Billing Number";
$recordTable{INTERMEDIATE}[26][0] = "Route Label";
$recordTable{INTERMEDIATE}[27][0] = "Route Attempt Number";
$recordTable{INTERMEDIATE}[28][0] = "Route Selected";
$recordTable{INTERMEDIATE}[29][0] = "Egress Local Signaling IP Address";
$recordTable{INTERMEDIATE}[30][0] = "Egress Remote Signaling IP Address";
$recordTable{INTERMEDIATE}[31][0] = "Ingress Trunk Group Name";
$recordTable{INTERMEDIATE}[32][0] = "Ingress PSTN Circuit End Point";
$recordTable{INTERMEDIATE}[33][0] = "Ingress IP Circuit End Point";
$recordTable{INTERMEDIATE}[34][0] = "Egress PSTN Circuit End Point";
$recordTable{INTERMEDIATE}[35][0] = "Egress IP Circuit End Point";
$recordTable{INTERMEDIATE}[36][0] = "Carrier Code";
$recordTable{INTERMEDIATE}[37][0] = "Call Group ID";
$recordTable{INTERMEDIATE}[38][0] = "Ingress Protocol Variant Specific Data";
$recordTable{INTERMEDIATE}[39][0] = "Ingress Signaling Type";
$recordTable{INTERMEDIATE}[40][0] = "Egress Signaling Type";
$recordTable{INTERMEDIATE}[41][0] = "Ingress Far End Switch Type";
$recordTable{INTERMEDIATE}[42][0] = "Egress Far End Switch Type";
$recordTable{INTERMEDIATE}[43][0] = "Carrier Code of Carrier who Owns iTG Far End";
$recordTable{INTERMEDIATE}[44][0] = "Carrier Code of Carrier who Owns eTG Far End";
$recordTable{INTERMEDIATE}[45][0] = "Calling Party Category";
$recordTable{INTERMEDIATE}[46][0] = "Dialed Number";
$recordTable{INTERMEDIATE}[47][0] = "Carrier Selection Information";
$recordTable{INTERMEDIATE}[48][0] = "Called Number Numbering Plan";
$recordTable{INTERMEDIATE}[49][0] = "Generic Address Parameter";
$recordTable{INTERMEDIATE}[50][0] = "Egress Trunk Group Name";
$recordTable{INTERMEDIATE}[51][0] = "Egress Protocol Variant Specific Data";
$recordTable{INTERMEDIATE}[52][0] = "Incoming Calling Number";
$recordTable{INTERMEDIATE}[53][0] = "Intermediate Record Reason";
$recordTable{INTERMEDIATE}[54][0] = "Originating Line Information (OLIP)";
$recordTable{INTERMEDIATE}[55][0] = "Jurisdiction Information Parameter (JIP)";
$recordTable{INTERMEDIATE}[56][0] = "Calling Party Nature of Address";
$recordTable{INTERMEDIATE}[57][0] = "Called Party Nature of Address";
$recordTable{INTERMEDIATE}[58][0] = "AMA Call Type";
$recordTable{INTERMEDIATE}[59][0] = "Message Billing Indicator (MBI)";
$recordTable{INTERMEDIATE}[60][0] = "LATA";
$recordTable{INTERMEDIATE}[61][0] = "Calling Party Presentation Restriction";
$recordTable{INTERMEDIATE}[62][0] = "Incoming ISUP Charge Number";
$recordTable{INTERMEDIATE}[63][0] = "Incoming ISUP Nature Of Address";
$recordTable{INTERMEDIATE}[64][0] = "Dialed Number Nature of Address";
$recordTable{INTERMEDIATE}[65][0] = "Global Call ID (GCID)";
$recordTable{INTERMEDIATE}[66][0] = "Charge Flag";
$recordTable{INTERMEDIATE}[67][0] = "AMA slp ID";
$recordTable{INTERMEDIATE}[68][0] = "AMA BAF Module";
$recordTable{INTERMEDIATE}[69][0] = "AMA Set Hex AB Indication";
$recordTable{INTERMEDIATE}[70][0] = "Service Feature ID";
$recordTable{INTERMEDIATE}[71][0] = "FE Parameter";
$recordTable{INTERMEDIATE}[72][0] = "Satellite Indicator";
$recordTable{INTERMEDIATE}[73][0] = "PSX Billing Info";
$recordTable{INTERMEDIATE}[74][0] = "Originating TDM Trunk Group Type";
$recordTable{INTERMEDIATE}[75][0] = "Terminating TDM Trunk Group Type";
$recordTable{INTERMEDIATE}[76][0] = "Ingress Trunk Member Number";
$recordTable{INTERMEDIATE}[77][0] = "Egress Trunk Group ID";
$recordTable{INTERMEDIATE}[78][0] = "Egress Switch ID";
$recordTable{INTERMEDIATE}[79][0] = "Ingress Local ATM Address";
$recordTable{INTERMEDIATE}[80][0] = "Ingress Remote ATM Address";
$recordTable{INTERMEDIATE}[81][0] = "Egress Local ATM Address";
$recordTable{INTERMEDIATE}[82][0] = "Egress Remote ATM Address";
$recordTable{INTERMEDIATE}[83][0] = "PSX Call Type";
$recordTable{INTERMEDIATE}[84][0] = "Outgoing Route Trunk Group ID";
$recordTable{INTERMEDIATE}[85][0] = "Outgoing Route Message ID";
$recordTable{INTERMEDIATE}[86][0] = "Incoming Route ID";
$recordTable{INTERMEDIATE}[87][0] = "Calling Name";
$recordTable{INTERMEDIATE}[88][0] = "Calling Name Type";
$recordTable{INTERMEDIATE}[89][0] = "Incoming Calling Party Numbering Plan";
$recordTable{INTERMEDIATE}[90][0] = "Outgoing Calling Party Numbering Plan";
$recordTable{INTERMEDIATE}[91][0] = "Calling Party Business Group ID";
$recordTable{INTERMEDIATE}[92][0] = "Called Party Business Group ID";
$recordTable{INTERMEDIATE}[93][0] = "Calling Party PPDN";
$recordTable{INTERMEDIATE}[94][0] = "Ticks from Setup Msg to Last Route Attempt";
$recordTable{INTERMEDIATE}[95][0] = "Ticks from Setup Msg to Rx of EXM";
$recordTable{INTERMEDIATE}[96][0] = "Ticks from Setup Msg to Generation of EXM";
$recordTable{INTERMEDIATE}[97][0] = "Billing Number Nature of Address";
$recordTable{INTERMEDIATE}[98][0] = "Incoming Calling Number Nature of Address";
$recordTable{INTERMEDIATE}[99][0] = "Egress Trunk Member Number";
$recordTable{INTERMEDIATE}[100][0] = "Selected Route Type";
$recordTable{INTERMEDIATE}[101][0] = "Telcordia Long Duration Record Type";
$recordTable{INTERMEDIATE}[102][0] = "Ticks From Previous Record";
$recordTable{INTERMEDIATE}[103][0] = "ISDN PRI Calling Party Subaddress";
$recordTable{INTERMEDIATE}[104][0] = "Outgoing Trunk Group Number in EXM";
$recordTable{INTERMEDIATE}[105][0] = "Ingress Local Signaling IP Address";
$recordTable{INTERMEDIATE}[106][0] = "Ingress Remote Signaling IP Address";
$recordTable{INTERMEDIATE}[107][0] = "Record Sequence Number";
$recordTable{INTERMEDIATE}[108][0] = "Transmission Medium Requirement";
$recordTable{INTERMEDIATE}[109][0] = "Information Transfer Rate";
$recordTable{INTERMEDIATE}[110][0] = "USI User Info Layer 1";
$recordTable{INTERMEDIATE}[111][0] = "Unrecognized Raw ISUP Calling Party Category";
$recordTable{INTERMEDIATE}[112][0] = "FSD: Release Link Trunking";
$recordTable{INTERMEDIATE}[113][0] = "FSD: Two B-Channel Transfer";
$recordTable{INTERMEDIATE}[114][0] = "Calling Party Business Unit";
$recordTable{INTERMEDIATE}[115][0] = "Called Party Business Unit";
$recordTable{INTERMEDIATE}[116][0] = "FSD: Redirecting";
$recordTable{INTERMEDIATE}[117][0] = "FSD: Ingress Release Link Trunking";
$recordTable{INTERMEDIATE}[118][0] = "PSX Index";
$recordTable{INTERMEDIATE}[119][0] = "PSX Congestion Level";
$recordTable{INTERMEDIATE}[120][0] = "PSX Processing Time (milliseconds)";
$recordTable{INTERMEDIATE}[121][0] = "Script Name";
$recordTable{INTERMEDIATE}[122][0] = "Ingress External Accounting Data";
$recordTable{INTERMEDIATE}[123][0] = "Egress External Accounting Data";
$recordTable{INTERMEDIATE}[124][0] = "Answer Supervision Type";
$recordTable{INTERMEDIATE}[125][0] = "Ingress Sip Refer or Sip Replaces Feature Specific Data";
$recordTable{INTERMEDIATE}[126][0] = "Egress Sip Refer or Sip Replaces Feature Specific Data";
$recordTable{INTERMEDIATE}[127][0] = "Network Transfers Feature Specific Data";
$recordTable{INTERMEDIATE}[128][0] = "Call Condition";
$recordTable{INTERMEDIATE}[129][0] = "Toll Indicator";
$recordTable{INTERMEDIATE}[130][0] = "Generic Number ( Number )";
$recordTable{INTERMEDIATE}[131][0] = "Generic Number Presentation Restriction Indicator";
$recordTable{INTERMEDIATE}[132][0] = "Generic Number Numbering Plan";
$recordTable{INTERMEDIATE}[133][0] = "Generic Number Nature of Address";
$recordTable{INTERMEDIATE}[134][0] = "Generic Number Type";
$recordTable{INTERMEDIATE}[135][0] = "Originating Trunk Type";
$recordTable{INTERMEDIATE}[136][0] = "Terminating Trunk Type";
$recordTable{INTERMEDIATE}[137][0] = "VPN Calling Public Presence Number";
$recordTable{INTERMEDIATE}[138][0] = "VPN Calling Private Presence Number";
$recordTable{INTERMEDIATE}[139][0] = "External Furnish Charging Info";
$recordTable{INTERMEDIATE}[140][0] = "Announcement Id  ";
$recordTable{INTERMEDIATE}[141][0] = "Network Data - Source Information";
$recordTable{INTERMEDIATE}[142][0] = "Network Data - Partition ID";
$recordTable{INTERMEDIATE}[143][0] = "Network Data - Network ID";
$recordTable{INTERMEDIATE}[144][0] = "Network Data - NCOS";
$recordTable{INTERMEDIATE}[145][0] = "ISDN access Indicator";
$recordTable{INTERMEDIATE}[146][0] = "Network Call Reference - Call Identity";
$recordTable{INTERMEDIATE}[147][0] = "Network Call Reference - Signaling Point Code";
$recordTable{INTERMEDIATE}[148][0] = "Ingress MIME Protocol Variant Specific Data";
$recordTable{INTERMEDIATE}[149][0] = "Egress MIME Protocol Variant Specific Data";
$recordTable{INTERMEDIATE}[150][0] = "Video Data - Video Bandwidth, Video Call Duration,Ingress/Egress IP video Endpoint, Video Codec";
$recordTable{INTERMEDIATE}[151][0] = "SVS Customer";
$recordTable{INTERMEDIATE}[152][0] = "SVS Vendor - Deprecated in 7.2.2 as part of Pcr1624";
$recordTable{INTERMEDIATE}[153][0] = "Remote GSX Billing Indicator";
$recordTable{INTERMEDIATE}[154][0] = "Call To Test PSX";
$recordTable{INTERMEDIATE}[155][0] = "Psx Overlap Route Requests";
$recordTable{INTERMEDIATE}[156][0] = "Ingress Bicc Info ";
$recordTable{INTERMEDIATE}[156][1] = "Circuit Identification Code ";
$recordTable{INTERMEDIATE}[156][2] = "Local Point Code";
$recordTable{INTERMEDIATE}[156][3] = "Remote Point Code ";
$recordTable{INTERMEDIATE}[156][4] = "Bearer Setup Mode";
$recordTable{INTERMEDIATE}[157][0] = "Egress Bicc Info ";
$recordTable{INTERMEDIATE}[157][1] = "Circuit Identification Code ";
$recordTable{INTERMEDIATE}[157][2] = "Local Point Code";
$recordTable{INTERMEDIATE}[157][3] = "Remote Point Code ";
$recordTable{INTERMEDIATE}[157][4] = "Bearer Setup Mode";
$recordTable{INTERMEDIATE}[158][0] = "Mlpp Precedence Level";
$recordTable{INTERMEDIATE}[159][0] = "Special Routing Information";
$recordTable{INTERMEDIATE}[160][0] = "Customer or Carrier Identifier";
$recordTable{INTERMEDIATE}[161][0] = "Service Type Identifier";
$recordTable{INTERMEDIATE}[162][0] = "Special Handling Information";
$recordTable{INTERMEDIATE}[163][0] = "Service Type Identifier";
$recordTable{INTERMEDIATE}[164][0] = "Itx charge information";
$recordTable{INTERMEDIATE}[165][0] = "GCR Global Charge Reference";
$recordTable{INTERMEDIATE}[166][0] = "PSX Name";
$recordTable{INTERMEDIATE}[167][0] = "No.of PSX tried ";
$recordTable{INTERMEDIATE}[168][0] = "Final Route Label";
$recordTable{INTERMEDIATE}[169][0] = "MTA Information";
$recordTable{INTERMEDIATE}[169][1] = "Origination Primary";
$recordTable{INTERMEDIATE}[169][2] = "Origination Secondary";
$recordTable{INTERMEDIATE}[169][3] = "Destination Primary";
$recordTable{INTERMEDIATE}[169][4] = "Destination Secondary";

$recordTable{SW_CHANGE}[1][0] = "Record Type";
$recordTable{SW_CHANGE}[2][0] = "Gateway Name";
$recordTable{SW_CHANGE}[3][0] = "Node Time Zone";
$recordTable{SW_CHANGE}[4][0] = "Record Date";
$recordTable{SW_CHANGE}[5][0] = "Record Time";
$recordTable{SW_CHANGE}[6][0] = "Old Software Version";
$recordTable{SW_CHANGE}[7][0] = "New Software Version";
$recordTable{SW_CHANGE}[8][0] = "Record Sequence Number";



#input:   nothing                        
#output:  array of known record types    
sub CamGetRecordTypes {                  
  return ( sort keys %recordTable );     
}                                        

#input:   recordType                     
#output:  1 if defined, 0 if undefined   
sub CamIsRecordDefined {                 
  if( $recordTable{$_[0]} ) {            
	return ( 1 );                        
  }                                      
  return ( 0 );                          
}                                        

# input:  recordType, fieldNumber        
# output: string describing the field    
sub CamGetFieldName {                    
  return ( $recordTable{$_[0]}[$_[1]][$_[2]] ); 
}                                        


$subFieldTable{"JAPAN"}[1] = "Protocol Variant ";
$subFieldTable{"JAPAN"}[2] = "UUI Sending Count ";
$subFieldTable{"JAPAN"}[3] = "UUI Receiving Count ";
$subFieldTable{"JAPAN"}[4] = "PSTN additional Calling party's category 1 ";
$subFieldTable{"JAPAN"}[5] = "Mobil additional Calling party's category 1 ";
$subFieldTable{"JAPAN"}[6] = "Mobil additional Calling party's category 2 ";
$subFieldTable{"JAPAN"}[7] = "Mobil additional Calling party's category 3 ";
$subFieldTable{"JAPAN"}[8] = "PSTN additional Called party's category 1 ";
$subFieldTable{"JAPAN"}[9] = "Mobil additional Called party's category 1 ";
$subFieldTable{"JAPAN"}[10] = "Mobil additional Called party's category 2 ";
$subFieldTable{"JAPAN"}[11] = "Mobil additional Called party's category 3 ";
$subFieldTable{"JAPAN"}[12] = "Called CA ";
$subFieldTable{"JAPAN"}[13] = "Calling CA ";
$subFieldTable{"JAPAN"}[14] = "Called IN Number ";
$subFieldTable{"JAPAN"}[15] = "Called Terminal Type ";
$subFieldTable{"JAPAN"}[16] = "Calling Terminal Type ";
$subFieldTable{"JAPAN"}[17] = "Unit rate indicator ";
$subFieldTable{"JAPAN"}[18] = "Initial lump-call rate ";
$subFieldTable{"JAPAN"}[19] = "First charging period ";
$subFieldTable{"JAPAN"}[20] = "Second charging period ";
$subFieldTable{"JAPAN"}[21] = "Third charging period ";
$subFieldTable{"JAPAN"}[22] = "Fourth charging period ";
$subFieldTable{"JAPAN"}[23] = "Contractor Number ";
$subFieldTable{"JAPAN"}[24] = "National/International call ";
$subFieldTable{"JAPAN"}[25] = "Original Called IN Number ";
$subFieldTable{"JAPAN"}[26] = "Redirecting Number ";
$subFieldTable{"JAPAN"}[27] = "Carrier Flag 1 ";
$subFieldTable{"JAPAN"}[28] = "Carrier Code 1 ";
$subFieldTable{"JAPAN"}[29] = "POI-CA Code 1 ";
$subFieldTable{"JAPAN"}[30] = "POI Level 1 ";
$subFieldTable{"JAPAN"}[31] = "Carrier Flag 2 ";
$subFieldTable{"JAPAN"}[32] = "Carrier Code 2 ";
$subFieldTable{"JAPAN"}[33] = "POI-CA Code 2 ";
$subFieldTable{"JAPAN"}[34] = "POI Level 2 ";
$subFieldTable{"JAPAN"}[35] = "Carrier Flag 3 ";
$subFieldTable{"JAPAN"}[36] = "Carrier Code 3 ";
$subFieldTable{"JAPAN"}[37] = "POI-CA Code 3 ";
$subFieldTable{"JAPAN"}[38] = "POI Level 3 ";
$subFieldTable{"JAPAN"}[39] = "Carrier Flag 4 ";
$subFieldTable{"JAPAN"}[40] = "Carrier Code 4 ";
$subFieldTable{"JAPAN"}[41] = "POI-CA Code 4 ";
$subFieldTable{"JAPAN"}[42] = "POI Level 4 ";
$subFieldTable{"JAPAN"}[43] = "Carrier Flag 5 ";
$subFieldTable{"JAPAN"}[44] = "Carrier Code 5 ";
$subFieldTable{"JAPAN"}[45] = "POI-CA Code 5 ";
$subFieldTable{"JAPAN"}[46] = "POI Level 5 ";
$subFieldTable{"JAPAN"}[47] = "Carrier Flag 6 ";
$subFieldTable{"JAPAN"}[48] = "Carrier Code 6 ";
$subFieldTable{"JAPAN"}[49] = "POI-CA Code 6 ";
$subFieldTable{"JAPAN"}[50] = "POI Level 6 ";
$subFieldTable{"JAPAN"}[51] = "Carrier Flag 7 ";
$subFieldTable{"JAPAN"}[52] = "Carrier Code 7 ";
$subFieldTable{"JAPAN"}[53] = "POI-CA Code 7 ";
$subFieldTable{"JAPAN"}[54] = "POI Level 7 ";
$subFieldTable{"JAPAN"}[55] = "SCP Carrier Code ";
$subFieldTable{"JAPAN"}[56] = "Additional POI-CA Code ";
$subFieldTable{"JAPAN"}[57] = "Transmission Medium Requirement ";
$subFieldTable{"JAPAN"}[58] = "Calling Party Subaddress ";
$subFieldTable{"JAPAN"}[59] = "Called Party Subaddress ";
$subFieldTable{"JAPAN"}[60] = "Cause of No Identification ";
$subFieldTable{"JAPAN"}[61] = "Charge indicator ";
$subFieldTable{"JAPAN"}[62] = "Number of CHG Messages ";
$subFieldTable{"JAPAN"}[63] = "Location ";
$subFieldTable{"JAPAN"}[64] = "Charge Rate Info Type ";
$subFieldTable{"JAPAN"}[65] = "Emergency Call Indicator ";
$subFieldTable{"JAPAN"}[66] = "SCP Donor Carrier Code ";
$subFieldTable{"JAPAN"}[67] = "SCP Recipient Carrier Code ";
$subFieldTable{"JAPAN"}[68] = "Transit Carrier Indicator ";
$subFieldTable{"JAPAN"}[69] = "Carrier Flag 8 ";
$subFieldTable{"JAPAN"}[70] = "Carrier Code 8 ";
$subFieldTable{"JAPAN"}[71] = "POI-CA Code 8 ";
$subFieldTable{"JAPAN"}[72] = "POI-Level 8 ";
$subFieldTable{"JAPAN"}[73] = "Carrier Flag 9 ";
$subFieldTable{"JAPAN"}[74] = "Carrier Code 9 ";
$subFieldTable{"JAPAN"}[75] = "POI-CA Code 9 ";
$subFieldTable{"JAPAN"}[76] = "POI-Level 9 ";
$subFieldTable{"JAPAN"}[77] = "Carrier Flag 10 ";
$subFieldTable{"JAPAN"}[78] = "Carrier Code 10 ";
$subFieldTable{"JAPAN"}[79] = "POI-CA Code 10 ";
$subFieldTable{"JAPAN"}[80] = "POI-Level 10 ";
$subFieldTable{"JAPAN"}[81] = "Carrier Flag 11 ";
$subFieldTable{"JAPAN"}[82] = "Carrier Code 11 ";
$subFieldTable{"JAPAN"}[83] = "POI-CA Code 11 ";
$subFieldTable{"JAPAN"}[84] = "POI-Level 11 ";
$subFieldTable{"JAPAN"}[85] = "Carrier Flag 12 ";
$subFieldTable{"JAPAN"}[86] = "Carrier Code 12 ";
$subFieldTable{"JAPAN"}[87] = "POI-CA Code 12 ";
$subFieldTable{"JAPAN"}[88] = "POI-Level 12 ";
$subFieldTable{"JAPAN"}[89] = "Carrier Flag 13 ";
$subFieldTable{"JAPAN"}[90] = "Carrier Code 13 ";
$subFieldTable{"JAPAN"}[91] = "POI-CA Code 13 ";
$subFieldTable{"JAPAN"}[92] = "POI-Level 13 ";
$subFieldTable{"JAPAN"}[93] = "Carrier Flag 14 ";
$subFieldTable{"JAPAN"}[94] = "Carrier Code 14 ";
$subFieldTable{"JAPAN"}[95] = "POI-CA Code 14 ";
$subFieldTable{"JAPAN"}[96] = "POI-Level 14 ";
$subFieldTable{"JAPAN"}[97] = "Calling Party Number - Screening Indicator ";
$subFieldTable{"JAPAN"}[98] = "Calling Party Number- Number Incomplete Indicator";
$subFieldTable{"JAPAN"}[99] = "Called Party Number-Internal Network Routing Indicator";
$subFieldTable{"JAPAN"}[100] = "Contractor Number-NOA ";
$subFieldTable{"JAPAN"}[101] = "Contractor Number-NPI ";
$subFieldTable{"JAPAN"}[102] = "Cause Value in ACM/CPG ";
$subFieldTable{"JAPAN"}[103] = "Pre-Subscription Indicator ";
$subFieldTable{"JAPAN"}[104] = "ISUP Preference Indicator ";
$subFieldTable{"JAPAN"}[105] = "Charge Information Type ";
$subFieldTable{"JAPAN"}[106] = "Visitor MA parameter ";
$subFieldTable{"JAPAN"}[107] = "Carrier Information Transfer Message and Type 1 ";
$subFieldTable{"JAPAN"}[108] = "Carrier Information Transfer Message and Type 2 ";
$subFieldTable{"JAPAN"}[109] = "Carrier Information Transfer Message and Type 3 ";
$subFieldTable{"JAPAN"}[110] = "Carrier Information Transfer Message and Type 4 ";
$subFieldTable{"JAPAN"}[111] = "Carrier Information Transfer Message and Type 5 ";
$subFieldTable{"JAPAN"}[112] = "Carrier Information Transfer Message and Type 6 ";
$subFieldTable{"JAPAN"}[113] = "Carrier Information Transfer Message and Type 7 ";
$subFieldTable{"JAPAN"}[114] = "Carrier Information Transfer Message and Type 8 ";
$subFieldTable{"JAPAN"}[115] = "Carrier Information Transfer Message and Type 9 ";
$subFieldTable{"JAPAN"}[116] = "Carrier Information Transfer Message and Type 10 ";
$subFieldTable{"JAPAN"}[117] = "Carrier Information Transfer Message and Type 11 ";
$subFieldTable{"JAPAN"}[118] = "Carrier Information Transfer Message and Type 12 ";
$subFieldTable{"JAPAN"}[119] = "Carrier Information Transfer Message and Type 13 ";
$subFieldTable{"JAPAN"}[120] = "Carrier Information Transfer Message and Type 14 ";
$subFieldTable{"JAPAN"}[121] = "SCP Carrier Code Message and Type ";
$subFieldTable{"JAPAN"}[122] = "Originating CPTT Received ";
$subFieldTable{"JAPAN"}[123] = "Terminating CPTT Received ";
$subFieldTable{"JAPAN"}[124] = "User Specific Called Party Sub Address ";
$subFieldTable{"JAPAN"}[125] = "User Specific Calling Party Sub Address ";
$subFieldTable{"JAPAN"}[126] = "Originating Trunkgroup Charge Area ";
$subFieldTable{"JAPAN"}[127] = "Terminating Trunkgroup Charge Area ";
$subFieldTable{"JAPAN"}[128] = "Called Directory Number NOA ";
$subFieldTable{"JAPAN"}[129] = "Called Directory Number NPI ";
$subFieldTable{"JAPAN"}[130] = "Called Directory Number INN ";
$subFieldTable{"JAPAN"}[131] = "Called Directory Number ";
$subFieldTable{"JAPAN"}[132] = "Raw Charge Information ";
$subFieldTable{"JAPAN"}[133] = "FCI ISDN User Part Ind - Iwk Ind ";
$subFieldTable{"JAPAN"}[134] = "BCI ISDN User Part Ind - Iwk Ind ";
$subFieldTable{"JAPAN"}[135] = "UUI 1 Msg and Direction - Octet count - Delivery  ";
$subFieldTable{"JAPAN"}[136] = "UUI 2 Msg and Direction - Octet count - Delivery  ";
$subFieldTable{"JAPAN"}[137] = "UUI 3 Msg and Direction - Octet count - Delivery  ";
$subFieldTable{"JAPAN"}[138] = "UUI 4 Msg and Direction - Octet count - Delivery  ";
$subFieldTable{"JAPAN"}[139] = "UUI 5 Msg and Direction - Octet count - Delivery  ";
$subFieldTable{"JAPAN"}[140] = "UUI 6 Msg and Direction - Octet count - Delivery  ";
$subFieldTable{"JAPAN"}[141] = "DPC Code1-Code2-Cgn Member-Cgn Member Ind-IGS/GC-0088 Prefix-ByPass ";
$subFieldTable{"JAPAN"}[142] = "JTI Cgn LS Subs-Cd LS Subs-ByPass-IGS/GC-Cd Member-Cd Member Ind ";
$subFieldTable{"JAPAN"}[143] = "Carrier Information Transfer Message and Type 15 ";
$subFieldTable{"JAPAN"}[144] = "Carrier Flag 15 ";
$subFieldTable{"JAPAN"}[145] = "Carrier Code 15 ";
$subFieldTable{"JAPAN"}[146] = "POI-CA Code 15 ";
$subFieldTable{"JAPAN"}[147] = "POI-Level 15 ";
$subFieldTable{"JAPAN"}[148] = "Carrier Information Transfer Message and Type 16 ";
$subFieldTable{"JAPAN"}[149] = "Carrier Flag 16 ";
$subFieldTable{"JAPAN"}[150] = "Carrier Code 16 ";
$subFieldTable{"JAPAN"}[151] = "POI-CA Code 16 ";
$subFieldTable{"JAPAN"}[152] = "POI-Level 16 ";
$subFieldTable{"JAPAN"}[153] = "Carrier Information Transfer Message and Type 17 ";
$subFieldTable{"JAPAN"}[154] = "Carrier Flag 17 ";
$subFieldTable{"JAPAN"}[155] = "Carrier Code 17 ";
$subFieldTable{"JAPAN"}[156] = "POI-CA Code 17 ";
$subFieldTable{"JAPAN"}[157] = "POI-Level 17 ";
$subFieldTable{"JAPAN"}[158] = "Carrier Information Transfer Message and Type 18 ";
$subFieldTable{"JAPAN"}[159] = "Carrier Flag 18 ";
$subFieldTable{"JAPAN"}[160] = "Carrier Code 18 ";
$subFieldTable{"JAPAN"}[161] = "POI-CA Code 18 ";
$subFieldTable{"JAPAN"}[162] = "POI-Level 18 ";
$subFieldTable{"JAPAN"}[163] = "Carrier Information Transfer Message and Type 19 ";
$subFieldTable{"JAPAN"}[164] = "Carrier Flag 19 ";
$subFieldTable{"JAPAN"}[165] = "Carrier Code 19 ";
$subFieldTable{"JAPAN"}[166] = "POI-CA Code 19 ";
$subFieldTable{"JAPAN"}[167] = "POI-Level 19 ";
$subFieldTable{"JAPAN"}[168] = "Carrier Information Transfer Message and Type 20 ";
$subFieldTable{"JAPAN"}[169] = "Carrier Flag 20 ";
$subFieldTable{"JAPAN"}[170] = "Carrier Code 20 ";
$subFieldTable{"JAPAN"}[171] = "POI-CA Code 20 ";
$subFieldTable{"JAPAN"}[172] = "POI-Level 20 ";
$subFieldTable{"JAPAN"}[173] = "Own Carrier Code matches received in IAM ";
$subFieldTable{"JAPAN"}[174] = "ACM/CPG Cause Coding Standard - Location ";
$subFieldTable{"JAPAN"}[175] = "REL Cause Coding Standard ";
$subFieldTable{"JAPAN"}[176] = "ACM/CPG Message Rcvd ";
$subFieldTable{"JAPAN"}[177] = "Calling Party Subaddress AFI Code ";
$subFieldTable{"JAPAN"}[178] = "Called Party Subaddress AFI Code ";
$subFieldTable{"JAPAN"}[179] = "Unrecognized Type Calling Party Subaddress ";
$subFieldTable{"JAPAN"}[180] = "Unrecognized Type Called Party Subaddress ";

$subFieldTable{"SIP"}[1] = "Protocol Variant ";
$subFieldTable{"SIP"}[2] = "Call ID ";
$subFieldTable{"SIP"}[3] = "From Field ";
$subFieldTable{"SIP"}[4] = "To Field ";
$subFieldTable{"SIP"}[5] = "Redirect Attemp Count ";
$subFieldTable{"SIP"}[6] = "Reserved";
$subFieldTable{"SIP"}[7] = "Display name of SIP URI PAI header ";
$subFieldTable{"SIP"}[8] = "User Parameter of P-K-CallForwardingLast Header ";
$subFieldTable{"SIP"}[9] = "Userinfo and Hostname of SIP Request URI Header ";
$subFieldTable{"SIP"}[10] = "Userinfo and Hostname of SIP URI PAI header ";
$subFieldTable{"SIP"}[11] = "Username parameter of the Proxy-Authorization header ";
$subFieldTable{"SIP"}[12] = "Displayname of Tel URI PAI header ";
$subFieldTable{"SIP"}[13] = "INVITE Contact header ";
$subFieldTable{"SIP"}[14] = "200OK-INVITE Contact header ";
$subFieldTable{"SIP"}[15] = "Redirecting Reason Parameter of P-K-CallForwardOriginal";
$subFieldTable{"SIP"}[16] = "Userinfo of Tel URI PAI header ";
$subFieldTable{"SIP"}[17] = "Contractor Number value of P-Sig-Info header ";
$subFieldTable{"SIP"}[18] = "ACK Received for 200 OK ";
$subFieldTable{"SIP"}[19] = "Status Msg for Call Release ";
$subFieldTable{"SIP"}[20] = "Reason Header value Q850 ";
$subFieldTable{"SIP"}[21] = "NAPT Status of the SIP SG for Signaling ";
$subFieldTable{"SIP"}[22] = "NAPT Status of the SIP SG for Media ";
$subFieldTable{"SIP"}[23] = "Original Peer SDP Address for NAPT ";
$subFieldTable{"SIP"}[24] = "UUI Sending Count ";
$subFieldTable{"SIP"}[25] = "UUI Receiving Count ";
$subFieldTable{"SIP"}[26] = "Service Information ";
$subFieldTable{"SIP"}[27] = "ICID ";
$subFieldTable{"SIP"}[28] = "Generated Host ";
$subFieldTable{"SIP"}[29] = "Originating IOI ";
$subFieldTable{"SIP"}[30] = "Terminating IOI ";
$subFieldTable{"SIP"}[31] = "P-K-Adn Header Number ";
$subFieldTable{"SIP"}[32] = "IP Address for FQDN calls or IP address of route header selected as next hop";
$subFieldTable{"SIP"}[33] = "Transport Protocol ";
$subFieldTable{"SIP"}[34] = "Direct Media Call ";
$subFieldTable{"SIP"}[35] = "Inbound SMM Indicator ";
$subFieldTable{"SIP"}[36] = "Outbound SMM Indicator ";
$subFieldTable{"SIP"}[37] = "Originating Charge Area ";
$subFieldTable{"SIP"}[38] = "Terminating Charge Area ";
$subFieldTable{"SIP"}[39] = "Feature Tag in Contact Header ";
$subFieldTable{"SIP"}[40] = "Feature Tag in Accept-Contact Header ";
$subFieldTable{"SIP"}[41] = "P-Charging-Function-Address ";
$subFieldTable{"SIP"}[42] = "P-Called-Party-Id";
$subFieldTable{"SIP"}[43] = "P-Visited-Network-Id";
$subFieldTable{"SIP"}[44] = "Direct Media with NAPT Call ";
$subFieldTable{"SIP"}[45] = "Ingress SMM Profile Name ";
$subFieldTable{"SIP"}[46] = "Egress SMM Profile Name ";
$subFieldTable{"SIP"}[47] = "P-Access-Network-Information header";
$subFieldTable{"SIP"}[48] = "IMS Node functionality";
$subFieldTable{"SIP"}[49] = "IMS node role";
$subFieldTable{"SIP"}[50] = "IMS Use PcfaCcf";
$subFieldTable{"SIP"}[51] = "P-CSCF calling party";
$subFieldTable{"SIP"}[52] = "P-CSCF called party";
$subFieldTable{"SIP"}[53] = "ICE used on Call ";
$subFieldTable{"SIP"}[54] = "ICE Complete - Time-stamp when ICE Completes ";
$subFieldTable{"SIP"}[55] = "Transit IOI List";
$subFieldTable{"SIP"}[56] = "Loop Back Ravel Call ";
$subFieldTable{"SIP"}[57] = "Optimal Media Routing Applied";
$subFieldTable{"SIP"}[58] = "IMS PAI Service Header";
$subFieldTable{"SIP"}[59] = "Feature-Caps header";
$subFieldTable{"SIP"}[60] = "Called Asserted Identity";
$subFieldTable{"SIP"}[61] = "NNI-Type ";
$subFieldTable{"SIP"}[62] = "Neighbour Address ";
$subFieldTable{"SIP"}[63] = "Relationship mode ";
$subFieldTable{"SIP"}[64] = "Session direction ";
$subFieldTable{"SIP"}[65] = "SMM CDR Field 1 ";
$subFieldTable{"SIP"}[66] = "SMM CDR Field 2 ";
$subFieldTable{"SIP"}[67] = "SMM CDR Field 3 ";
$subFieldTable{"SIP"}[68] = "SMM CDR Field 4 ";
$subFieldTable{"SIP"}[69] = "SMM CDR Field 5 ";

$subFieldTable{"SIP-T"}[1] = "Protocol Variant ";
$subFieldTable{"SIP-T"}[2] = "Call ID ";
$subFieldTable{"SIP-T"}[3] = "From Field ";
$subFieldTable{"SIP-T"}[4] = "To Field ";
$subFieldTable{"SIP-T"}[5] = "Redirect Attempt Count ";
$subFieldTable{"SIP-T"}[6] = "SIP-T Version ";
$subFieldTable{"SIP-T"}[7] = "Display name of SIP URI PAI header ";
$subFieldTable{"SIP-T"}[8] = "User Parameter of P-K-CallForwardingLast Header ";
$subFieldTable{"SIP-T"}[9] = "Userinfo and Hostname of SIP Request URI Header ";
$subFieldTable{"SIP-T"}[10] = "Userinfo and Hostname of SIP URI PAI header ";
$subFieldTable{"SIP-T"}[11] = "Username parameter of the Proxy-Authorization header ";
$subFieldTable{"SIP-T"}[12] = "Displayname of Tel URI PAI header ";
$subFieldTable{"SIP-T"}[13] = "INVITE Contact header ";
$subFieldTable{"SIP-T"}[14] = "200OK-INVITE Contact header ";
$subFieldTable{"SIP-T"}[15] = "Redirecting Reason Parameter of P-K-CallForwardOriginal";
$subFieldTable{"SIP-T"}[16] = "Userinfo of Tel URI PAI header ";
$subFieldTable{"SIP-T"}[17] = "Contractor Number value of P-Sig-Info header ";
$subFieldTable{"SIP-T"}[18] = "ACK Received for 200 OK ";
$subFieldTable{"SIP-T"}[19] = "Status Msg for Call Release ";
$subFieldTable{"SIP-T"}[20] = "Reason Header value Q850 ";
$subFieldTable{"SIP-T"}[21] = "NAPT Status of the SIP SG for Signaling ";
$subFieldTable{"SIP-T"}[22] = "NAPT Status of the SIP SG for Media ";
$subFieldTable{"SIP-T"}[23] = "Original Peer SDP Address for NAPT ";
$subFieldTable{"SIP-T"}[24] = "UUI Sending Count ";
$subFieldTable{"SIP-T"}[25] = "UUI Receiving Count ";
$subFieldTable{"SIP-T"}[26] = "Service Information ";
$subFieldTable{"SIP-T"}[27] = "ICID ";
$subFieldTable{"SIP-T"}[28] = "Generated Host ";
$subFieldTable{"SIP-T"}[29] = "Originating IOI ";
$subFieldTable{"SIP-T"}[30] = "Terminating IOI ";
$subFieldTable{"SIP-T"}[31] = "P-K-Adn Header Number ";
$subFieldTable{"SIP-T"}[32] = "IP Address for FQDN calls or IP address of route header selected as next hop";
$subFieldTable{"SIP-T"}[33] = "Transport Protocol ";
$subFieldTable{"SIP-T"}[34] = "Direct Media Call ";
$subFieldTable{"SIP-T"}[35] = "Inbound SMM Status ";
$subFieldTable{"SIP-T"}[36] = "Outbound SMM Status ";
$subFieldTable{"SIP-T"}[37] = "Originating Charge Area ";
$subFieldTable{"SIP-T"}[38] = "Terminating Charge Area ";
$subFieldTable{"SIP-T"}[39] = "Feature Tag in Contact Header ";
$subFieldTable{"SIP-T"}[40] = "Feature Tag in Accept-Contact Header ";
$subFieldTable{"SIP-T"}[41] = "P-Charging-Function-Address ";
$subFieldTable{"SIP-T"}[42] = "P-Called-Party-Id";
$subFieldTable{"SIP-T"}[43] = "P-Visited-Network-Id";
$subFieldTable{"SIP-T"}[44] = "Direct Media with NAPT Call ";
$subFieldTable{"SIP-T"}[45] = "Ingress SMM Profile Name ";
$subFieldTable{"SIP-T"}[46] = "Egress SMM Profile Name ";
$subFieldTable{"SIP-T"}[47] = "P-Access-Network-Information header";
$subFieldTable{"SIP-T"}[48] = "IMS Node functionality";
$subFieldTable{"SIP-T"}[49] = "IMS node role";
$subFieldTable{"SIP-T"}[50] = "IMS Use PcfaCcf";
$subFieldTable{"SIP-T"}[51] = "P-CSCF calling party";
$subFieldTable{"SIP-T"}[52] = "P-CSCF called party";
$subFieldTable{"SIP-T"}[53] = "ICE used on Call";
$subFieldTable{"SIP-T"}[54] = "ICE Complete - Time-stamp when ICE Completes";
$subFieldTable{"SIP-T"}[55] = "Transit IOI";
$subFieldTable{"SIP-T"}[56] = "Loop Back Ravel Call ";
$subFieldTable{"SIP-T"}[57] = "Optimal Media Routing Applied";
$subFieldTable{"SIP-T"}[58] = "IMS PAI Service Header";
$subFieldTable{"SIP-T"}[59] = "Feature-Caps header";
$subFieldTable{"SIP-T"}[60] = "Called Asserted Identity";
$subFieldTable{"SIP-T"}[61] = "NNI-Type ";
$subFieldTable{"SIP-T"}[62] = "Neighbour Address ";
$subFieldTable{"SIP-T"}[63] = "Relationship mode ";
$subFieldTable{"SIP-T"}[64] = "Session direction ";
$subFieldTable{"SIP-T"}[65] = "SMM CDR Field 1 ";
$subFieldTable{"SIP-T"}[66] = "SMM CDR Field 2 ";
$subFieldTable{"SIP-T"}[67] = "SMM CDR Field 3 ";
$subFieldTable{"SIP-T"}[68] = "SMM CDR Field 4 ";
$subFieldTable{"SIP-T"}[69] = "SMM CDR Field 5 ";

$subFieldTable{"GSX2GSX"}[1] = "Protocol Variant ";
$subFieldTable{"GSX2GSX"}[2] = "Gateway to Gateway Handle ";

$subFieldTable{"BT-IUP"}[1] = "Protocol Variant ";
$subFieldTable{"BT-IUP"}[2] = "Presentation Number Nature of Address ";
$subFieldTable{"BT-IUP"}[3] = "Presentation Number Address Restriction Ind ";
$subFieldTable{"BT-IUP"}[4] = "Presentation Number Screening Indicator ";
$subFieldTable{"BT-IUP"}[5] = "Presentation Number Digits ";
$subFieldTable{"BT-IUP"}[6] = "Partial CLI Digits ";
$subFieldTable{"BT-IUP"}[7] = "Release Reason ";
$subFieldTable{"BT-IUP"}[8] = "Malicious Call Trace  ";
$subFieldTable{"BT-IUP"}[9] = "Service Information ";

$subFieldTable{"UKISUP"}[1] = "Protocol Variant ";
$subFieldTable{"UKISUP"}[2] = "Presentation Number Nature of Address ";
$subFieldTable{"UKISUP"}[3] = "Presentation Number Address Restriction Ind ";
$subFieldTable{"UKISUP"}[4] = "Presentation Number Screening Indicator ";
$subFieldTable{"UKISUP"}[5] = "Presentation Number Digits ";
$subFieldTable{"UKISUP"}[6] = "Partial CLI Digits ";
$subFieldTable{"UKISUP"}[7] = "Release Reason ";
$subFieldTable{"UKISUP"}[8] = "Malicious Call Trace  ";
$subFieldTable{"UKISUP"}[9] = "Service Information ";

$subFieldTable{"ARGENTINA"}[1] = "Protocol Variant ";
$subFieldTable{"ARGENTINA"}[2] = "Exchange Identification ";
$subFieldTable{"ARGENTINA"}[3] = "Route Identification ";
$subFieldTable{"ARGENTINA"}[4] = "Circuit Identity ";

$subFieldTable{"ARGENTINAIDT"}[1] = "Protocol Variant ";
$subFieldTable{"ARGENTINAIDT"}[2] = "Exchange Identification ";
$subFieldTable{"ARGENTINAIDT"}[3] = "Route Identification ";
$subFieldTable{"ARGENTINAIDT"}[4] = "Circuit Identity ";

$subFieldTable{"INDIA"}[1] = "Protocol Variant ";
$subFieldTable{"INDIA"}[2] = "Charge Band ";

$subFieldTable{"H323"}[1] = "Protocol Variant ";
$subFieldTable{"H323"}[2] = "H323 Call Identifier ";
$subFieldTable{"H323"}[3] = "H323 Conference Identifier ";
$subFieldTable{"H323"}[4] = "H323 Conference Referenece Value - CRV ";

$subFieldTable{"PORTUGAL-ONI"}[1] = "Protocol Variant ";
$subFieldTable{"PORTUGAL-ONI"}[2] = "Call Indentity ";
$subFieldTable{"PORTUGAL-ONI"}[3] = "Signalling Point Code ";

$subFieldTable{"SLOVAK2"}[1] = "Protocol Variant ";
$subFieldTable{"SLOVAK2"}[2] = "Charge Band ";

$subFieldTable{"RLT"}[1] = "Feature Identifier ";
$subFieldTable{"RLT"}[2] = "Number of Sub-Fields to Follow ";
$subFieldTable{"RLT"}[3] = "IAM GD Billing Number ";
$subFieldTable{"RLT"}[4] = "IAM GD Universal Access Number ";
$subFieldTable{"RLT"}[5] = "IAM GD Originating Switch ID ";
$subFieldTable{"RLT"}[6] = "IAM GD Originating Trunk ID ";
$subFieldTable{"RLT"}[7] = "Billing FAR GD Billing Number ";
$subFieldTable{"RLT"}[8] = "Billing FAR GD Universal Access Num ";
$subFieldTable{"RLT"}[9] = "Billing FAR GD Originating Switch ID ";
$subFieldTable{"RLT"}[10] = "Billing FAR GD Originating Trunk ID ";
$subFieldTable{"RLT"}[11] = "Time Elapsed from Rx of AR Setup Msg ";
$subFieldTable{"RLT"}[12] = "Redirecting FAR GD Billing Number ";
$subFieldTable{"RLT"}[13] = "Redirecting FAR GD Universal Access Num ";
$subFieldTable{"RLT"}[14] = "Redirecting FAR GD Originating Switch ID ";
$subFieldTable{"RLT"}[15] = "Redirecting FAR GD Originating Trunk ID ";
$subFieldTable{"RLT"}[16] = "Redirecting FAR Called Party Number ";
$subFieldTable{"RLT"}[17] = "Redirecting FAR Calling Party Number ";
$subFieldTable{"RLT"}[18] = "Redirecting FAR Charge Number ";
$subFieldTable{"RLT"}[19] = "Redirecting FAR Originating Line Info ";
$subFieldTable{"RLT"}[20] = "Redirecting FAR Attempt Failed Counter ";
$subFieldTable{"RLT"}[21] = "Time Elapsed from Rx of AR Setup Msg ";
$subFieldTable{"RLT"}[22] = "Time Elapsed from Rx of AR Setup Msg ";
$subFieldTable{"RLT"}[23] = "Bridging FAR GD Billing Number ";
$subFieldTable{"RLT"}[24] = "Bridging FAR GD Universal Access Number ";
$subFieldTable{"RLT"}[25] = "Bridging FAR GD Originating Switch ID ";
$subFieldTable{"RLT"}[26] = "Bridging FAR GD Originating Trunk ID ";
$subFieldTable{"RLT"}[27] = "Bridging FAR Called Party Number ";
$subFieldTable{"RLT"}[28] = "Bridging FAR Calling Party Number ";
$subFieldTable{"RLT"}[29] = "Bridging FAR Call Reference ";
$subFieldTable{"RLT"}[30] = "Bridging FAR Attempt Failed Counter ";
$subFieldTable{"RLT"}[31] = "Time Elapsed from Rx of AR Setup Msg ";
$subFieldTable{"RLT"}[32] = "Time Elapsed from Rx of AR Setup Msg to ";

$subFieldTable{"REDI"}[1] = "Feature Identifier ";
$subFieldTable{"REDI"}[2] = "Number of Sub-Fields to Follow ";
$subFieldTable{"REDI"}[3] = "Redirecting Number ";
$subFieldTable{"REDI"}[4] = "Original Redirecting Called Number ";
$subFieldTable{"REDI"}[5] = "Redirection Reason ";
$subFieldTable{"REDI"}[6] = "Original Redirection Reason ";
$subFieldTable{"REDI"}[7] = "Redirection Counter ";
$subFieldTable{"REDI"}[8] = "Redirecting Number (Addr Pres Rest) ";
$subFieldTable{"REDI"}[9] = "Redirecting Number (Numbering Plan) ";
$subFieldTable{"REDI"}[10] = "Redirecting Number (NOA) ";
$subFieldTable{"REDI"}[11] = "Redirection Number (Number) ";
$subFieldTable{"REDI"}[12] = "Redirection Number (Numbering Plan) ";
$subFieldTable{"REDI"}[13] = "Redirection Number (NOA) ";
$subFieldTable{"REDI"}[14] = "Redirection Capability ";
$subFieldTable{"REDI"}[15] = "Redirect Forward Inf (Information Type) ";
$subFieldTable{"REDI"}[16] = "Redirect Forward Inf (Redirection Reason) ";
$subFieldTable{"REDI"}[17] = "Redirect Forward Inf (Redirection Poss) ";
$subFieldTable{"REDI"}[18] = "Redirect Backward Inf (Information Type) ";
$subFieldTable{"REDI"}[19] = "Redirect Backward Inf (Redirection Reason) ";
$subFieldTable{"REDI"}[20] = "Number of Redirections ";
$subFieldTable{"REDI"}[21] = "Redirection Executed ";
$subFieldTable{"REDI"}[22] = "Original Redirecting Called Number (NOA) ";
$subFieldTable{"REDI"}[23] = "Redirection number presentation indicator ";
$subFieldTable{"REDI"}[24] = "Call Diversion Information (Redirecting reason) ";
$subFieldTable{"REDI"}[25] = "Call Diversion Information (Notification  subscription option) ";

$subFieldTable{"SREF"}[1] = "Feature Identifier ";
$subFieldTable{"SREF"}[2] = "Number of Sub-Fields to Follow ";
$subFieldTable{"SREF"}[3] = "Time Elapsed from Receipt of INVITE Msg ";
$subFieldTable{"SREF"}[4] = "Transferor ";
$subFieldTable{"SREF"}[5] = "New transfer target ";

$subFieldTable{"SREPL"}[1] = "Feature Identifier ";
$subFieldTable{"SREPL"}[2] = "Number of Sub-Fields to Follow ";
$subFieldTable{"SREPL"}[3] = "Time Elapsed from Receipt of first call's ";
$subFieldTable{"SREPL"}[4] = "Operation performed on this call's leg ";
$subFieldTable{"SREPL"}[5] = "This call's leg ID ";
$subFieldTable{"SREPL"}[6] = "Peer call's GCID ";
$subFieldTable{"SREPL"}[7] = "Peer call's leg ID ";

$subFieldTable{"SREFREPL"}[1] = "Feature Identifier ";
$subFieldTable{"SREFREPL"}[2] = "Number of Sub-Fields to Follow ";
$subFieldTable{"SREFREPL"}[3] = "Time Elapsed from Receipt of initial ";
$subFieldTable{"SREFREPL"}[4] = "Operation performed on this call's leg ";
$subFieldTable{"SREFREPL"}[5] = "This call's leg ID ";
$subFieldTable{"SREFREPL"}[6] = "Peer call's GCID ";
$subFieldTable{"SREFREPL"}[7] = "Peer call's leg ID ";

$subFieldTable{"NWXF"}[1] = "Feature Identifier ";
$subFieldTable{"NWXF"}[2] = "Number of Sub-Fields to Follow ";
$subFieldTable{"NWXF"}[3] = "Speed Dial Digits ";
$subFieldTable{"NWXF"}[4] = "RefTod ";
$subFieldTable{"NWXF"}[5] = "TermCallType ";



# input:  recordType, fieldNumber        
# output: string describing the field    
sub CamGetSubFieldName {                 
  return( $subFieldTable{$_[0]}[$_[1]] );
}                                        

#input:   subFieldType                   
#output:  1 if defined, 0 if undefined   
sub CamIsSubFieldDefined {               
  if( $subFieldTable{$_[0]} ) {          
	return ( 1 );                        
  }                                      
  return ( 0 );                          
}                                        




#  
#  
# The rest of this file has been generated by copying camParser.pl 
#  
#  



###########################################################
# Sonus Networks, Inc.
#
# Marlin Switch
#
# All Rights Reserved.
#
# Module Name:
# 	/software/src/marlin/TOOLS/perlscripts/camParser.pl
#
# Module Sescription:
# 	This script parses GSX generated .ACT files (aka CAM files)
#   and presents a more readable, formatted output.
#   
#   This file needs the perl module 'camRecordTable.pm' to run,
#   which is generated by 'camBulder.pl'.
#
#     usage: camParser.pl [options] <data>  -or-  <data> | camParser.pl [options]
#
#	Options added by H.Hamblin on June 6th 2006
#		-a		Prints CDR fields in Automation format
#
#		-d		Prints a decode header for start and end of 
#				individual ACT record
#
#		-r <REC_TYPE>	Allows specified record types to be parsed. 
#				Multiple record types can be seperated by |. 
#
#		-t		Displays raw ACT data
#
#		-u		Do NOT Display "Unknown" before unknown field
#
#		-v <VARIANT>	Displays only the specified variant data 
#                               Must be used in conjunction with -r option.
#
# Author and Date:
# 	Michael Siedzik x8583         Created Aug 29, 2003.
#
###########################################################

use Getopt::Std;

package main;

getopts("adhtur:v:");

if ($main::opt_h) {
	print "usage: camParser.pl [options] <data>\n";
	print " Options: \n";
	print "      -a              Prints CDR fields in automation format.\n"; 
	print "                        e.g. STOP:F17:Call Direction:\"PSTN-TO-IP\".\n";
	print "      -d              Prints a decode header to mark start and end of individual ACT record.\n";
	print "      -r <REC_TYPE>   Only parse specified record type(s) <REC_TYPE> to parsed.\n";
	print "                      Multiple record types can be seperated by \"|\".\n"; 
	print "      -t              Displays raw ACT data as well as parsed output.\n"; 
	print "      -u              Prevents \"Unknown\" being prefixed before unknown parsed fields.\n";
	print "      -v <VARIANT>    Display only the specified variant data if it exists.\n";
	print "                      Must be used in conjunction with -r option\n\n";
	exit 0;
}


if ($main::opt_r) {
	if (!(($main::opt_r =~ /START/) ||
	       ($main::opt_r =~ /STOP/) ||
	       ($main::opt_r =~ /ATTEMPT/) ||
	       ($main::opt_r =~ /INTERMEDIATE/) ||
	       ($main::opt_r =~ /SW_CHANGE/)))
	{
		print "Warning: Option -r <record_type> has incorrect Record Type '$main::opt_r'\n";
		print "Valid values are as follows:\n";
		print " 'START'\n 'STOP'\n 'ATTEMPT'\n 'INTERMEDIATE'\n 'SW_CHANGE'\n";
      
		exit 1;
	}
}

if ($main::opt_v) {
	if (($main::opt_v ne "JAPAN") &&
	    ($main::opt_v ne "SIP") &&
	    ($main::opt_v ne "SIP-T") &&
	    ($main::opt_v ne "GSX2GSX") &&
	    ($main::opt_v ne "BT-IUP") &&
	    ($main::opt_v ne "UKISUP") &&
	    ($main::opt_v ne "ARGENTINA") &&
	    ($main::opt_v ne "INDIA") &&
	    ($main::opt_v ne "H323") &&
	    ($main::opt_v ne "PORTUGAL-ONI") &&
	    ($main::opt_v ne "RLT") &&
	    ($main::opt_v ne "REDI") &&
	    ($main::opt_v ne "SREF") &&
	    ($main::opt_v ne "SRP") &&
	    ($main::opt_v ne "NWXF")) 
	{
		print "Warning: Option -v has incorrect Variant string '$main::opt_v'\n";
		print "Valid values are as follows:\n";
		print " 'ARGENTINA'\n 'BT-IUP'\n 'GSX2GSX'\n 'H323'\n 'INDIA'\n 'JAPAN'\n 'NWXF'\n"; 
		print " 'PORTUGAL-ONI'\n 'REDI'\n 'RLT'\n 'SIP'\n 'SIP-T'\n 'SREF'\n 'SRP'\n 'UKISUP'\n\n";
	
		exit 1;
	} 
	elsif (! $main::opt_r)
	{

		# Variant string specified by option -v is valid
		# Ensure option -r is specified. If not then -v <variant> has to be used with -r <record_type>

		print "Warning: Option -v <variant> has to be used in conjunction with -r <record_type>\n";

		exit 1;
	}
}

# Initialise recordNum
$recordNum=0;

# Initilise processingACTFields
$processingACTFields=0;


# read records from standard input
@records = <>;

foreach $record (@records)
{
	# split this record up into fields
	# the delimiter used is comma, so we have to do some tricks
	# to avoid splitting double quote delimited fileds (i.e., PVSD)

    # The use of chomp has been removed because if you have a lot of blank
    # fields at the end of the record the printing stops on the last field
    # which contains a value.
    #chomp($record);

	if (($record =~ /^START/) || 
	    ($record =~ /^STOP/) ||
	    ($record =~ /^ATTEMPT/) ||
	    ($record =~ /^INTERMEDIATE/) ||
	    ($record =~ /^SW_CHANGE/))
	{ 

		if ($main::opt_t) {
			print "\n\n", $record, "\n\n";
		}

		@fields = split(',', $record);
		$recordNum++;

		chomp($fields[0]);
		
		if (!($main::opt_a)) 
		{
			print "Record $recordNum '$fields[0]'\n";
		}

		$recordType=$fields[0];

		#
		# record type is known, here we go!
		#
		$recordCnt{$fields[0]}++;

		$fieldNum = 0;
		$subfield = 0;

		# set print_record to 1 (true) by default for each record
		$print_record = 1;

		# set print_subfield_only to 0 (false) by default
		$print_subfield_only = 0;

		# If Option -r <record_type> is specified and <record_type> is not equal
		# to the current record defined by $field[0] then set $print_record to 0 (false);
		# print_record is 1 by default
		if (($main::opt_r) && (!($main::opt_r =~ /$fields[0]/)))
		{ 
			$print_record = 0;
		}

		# If Option -v <variant> and option -r <record_type> are specifed
		# then set the $print_subfield_only var to 1 (true)
		if (($main::opt_v) && ($main::opt_r)) 
		{
			$print_subfield_only = 1;
		}
	
		if ($print_record)
		{ 

			if ( ($processingACTFields == 0) && ($main::opt_d) ) {
				print "==================================================================================\n";
				print "CDR \"$fields[0]\" Record - CAMDUMP DECODE BEGIN\n";
				print "==================================================================================\n";
				$processingACTFields=1;
			}

			foreach $field (@fields)
			{
				# Copy $field var to $field_prtStr var. If Option -a is specified then $field_prtStr
				# will be changed to remove quotes. The $field var is checked for quotes later to
				# see if the end of the subfields has been reached.
				#
				$field_prtStr = $field;

				# Option -c specifed so remove quotes from $field_prtStr
				if ($main::opt_a)
				{ 
					$field_prtStr =~ s/\"//g;
				}


				# Check to see if we are parsing subfields...
				#
				if ( $subfield == 0 )
				{
					# 
					# print field number, field name and a colon
					#
					$fieldNum++;

					# Only print if $print_subfield_only is false 
					# OR $fieldNum is 1 i.e. the Record Type field
					#
					if ((! $print_subfield_only ) || ($fieldNum == 1))
					{
						if ($main::opt_a)
						{
							printf "\n${recordType}:F%d:%s:", $fieldNum, CamGetFieldName($fields[0],$fieldNum,0);	
						} else {
							printf "\n %3d. %-45s: ", $fieldNum, CamGetFieldName($fields[0],$fieldNum,0);	
						}
					}
			
					# if this field starts with a double quote,
					# and it doesn't end in a double quote,
					#   then it is the start of a subfield. 
					#
					if ( ( $field =~ m/^\"/ ) && ( $field !~ m/\"$/ ) )
					{
						# print <CR> then subfield #1
						$subfield++;
				
						# remove the " to obtain the type of SubField e.g.  "JAPAN
						($ctrlchar, $subfieldType) = split(/\"/, $field, 2);

						# If the $print_subfield_only var is true and option -v <VARIANT> 
						# contains the $subfieldType 
						# OR 
						# option -v is not defined 
						# then print the subfields 
						#
						if (($print_subfield_only && ($main::opt_v =~ /$subfieldType/)) || (! $main::opt_v))
						{
							# Obtain SubField Description, empty if no Description available
						    if( CamIsSubFieldDefined( $subfieldType ) )
							{
							    $subfieldDesc = CamGetSubFieldName($subfieldType,$subfield);
							}
							else
							{
							    $subfieldDesc = CamGetFieldName($fields[0],$fieldNum,$subfield);
							}

							# Option -a specified? 
							if ($main::opt_a) 
							{
								# Print in automation format i.e. without spaces and using '='	
								printf "\n${recordType}:F%d-%d:%s:\"%s\"",$fieldNum,$subfield,$subfieldDesc,$field_prtStr;
							} else {	
								# Print in standard format	
								printf "\n     %3d.%-2d %-44s: %s", $fieldNum, $subfield, $subfieldDesc, $field_prtStr;
							}
						}
					}
					elsif ((! $print_subfield_only ) || ($fieldNum == 1))
					{
						# Nope, just print the field
						if ($main::opt_a) {
							printf "\"%s\"", $field_prtStr;
						} else {
							printf "%s", $field_prtStr;
						}
					}
				}
				elsif (($print_subfield_only && ($main::opt_v =~ /$subfieldType/)) || (! $main::opt_v))
				{
					#
					# continue printing subfields
					#
					$subfield++;
					if( CamIsSubFieldDefined( $subfieldType ) )
					{
						$subfieldDesc = CamGetSubFieldName($subfieldType,$subfield);
					}
					else
					{
						$subfieldDesc = CamGetFieldName($fields[0],$fieldNum,$subfield);
					}

					# Is Option -a specified?
					if ($main::opt_a) 
					{
						# Print in automation format i.e. without spaces and using '='
						printf "\n${recordType}:F%d-%d:%s:\"%s\"",$fieldNum,$subfield,$subfieldDesc, $field_prtStr;	
					} 
					else 
					{
						# Print in standard format
						printf "\n     %3d.%-2d %-44s:  %s", $fieldNum, $subfield, $subfieldDesc, $field_prtStr;
					}
			
					# if this field ends with a double quote
					if ( $field =~ m/\"$/ )
					{
						# then we are done parsing subfields
						$subfield = 0;
					}
				}
			}
	
			print "\n";

			if ( ($processingACTFields == 1) && ($main::opt_d) ) {
				print "==================================================================================\n";
				print "CDR \"$fields[0]\" Record - CAMDUMP DECODE END\n";
				print "==================================================================================\n";
				$processingACTFields=0;
			}
		}
	} else {
	
		## Record is Unknown
		##
		if (!($main::opt_u))
		{
			printf "Unknown :%s",$record;
			print "\n   ", $record, "\n";
			$recordCnt{"MISC"}++;
		} else {
			print $record, "\n";
		}
	}
}

if (!($main::opt_a)) 
{
	#
	# Print a little historgram for each record type
	#
	foreach $key (sort keys %recordCnt)
	{
		print $recordCnt{$key}, " ", $key;
		print "s" if ($recordCnt{$key}>1);
		print "\n";
	}
}

print "\n";

exit 0;
